import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-session-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8"};
const T=(v:unknown)=>String(v??"").trim();
const L=(v:unknown)=>T(v).toLowerCase();
const J=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Cache-Control":"no-store"}});
const URL=Deno.env.get("SUPABASE_URL")!;
function secret(){const packed=Deno.env.get("SUPABASE_SECRET_KEYS");if(packed){try{const p=JSON.parse(packed);if(p?.default)return String(p.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||""}
const sb=createClient(URL,secret(),{auth:{persistSession:false,autoRefreshToken:false}});
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function normRole(v:unknown){const s=L(v).replace(/[-\s]+/g,"_").replace(/[^a-z0-9_]/g,"");if(s==="admin")return"admin";if(s==="hrd")return"hrd";return s}
async function auth(req:Request){const token=T(req.headers.get("x-session-token"));if(!token)return null;const{data:ss}=await sb.from("user_sessions").select("user_account_id,expires_at,revoked_at").eq("token_hash",await sha(token)).maybeSingle();if(!ss||ss.revoked_at||!ss.expires_at||Date.parse(ss.expires_at)<=Date.now())return null;const{data:a}=await sb.from("user_accounts").select("id,teacher_id,username,status").eq("id",ss.user_account_id).maybeSingle();if(!a||["nonaktif","inactive","disabled","blocked"].includes(L(a.status)))return null;const roles:string[]=[normRole(a.username)];const{data:r}=await sb.from("user_account_roles").select("role_code,role,is_active").eq("user_account_id",a.id).eq("is_active",true);for(const x of r||[])roles.push(normRole(x.role_code||x.role));if(a.teacher_id){const{data:ur}=await sb.from("user_roles").select("role_code,is_active").eq("teacher_id",a.teacher_id).eq("is_active",true);for(const x of ur||[])roles.push(normRole(x.role_code))}return roles.some(x=>x==="hrd"||x==="admin")?{...a,roles:[...new Set(roles.filter(Boolean))]}:null}
function monthBounds(v:unknown){const month=T(v)||new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))throw Error("invalid_month");const[y,m]=month.split("-").map(Number);return{month,start:month+"-01",end:new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}}
function isSaturday(v:string){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v+"T12:00:00Z").getUTCDay()===6}
function mins(v:string){if(!/^\d{2}:\d{2}$/.test(v))return null;const[h,m]=v.split(":").map(Number);return h*60+m}
async function context(date:string){const{data:unit}=await sb.from("school_units").select("id").eq("code","SD").maybeSingle();if(!unit)throw Error("school_unit_not_found");let yq=sb.from("academic_years").select("id,name").eq("school_unit_id",unit.id).lte("start_date",date).gte("end_date",date).order("start_date",{ascending:false}).limit(1);const{data:ys}=await yq;if(!ys?.[0])throw Error("academic_year_not_found");const year=ys[0];const{data:sem}=await sb.from("semesters").select("semester_no").eq("academic_year_id",year.id).lte("start_date",date).gte("end_date",date).limit(1).maybeSingle();return{unitId:unit.id,yearId:year.id,yearName:year.name,semesterNo:Number(sem?.semester_no||1)}}
async function bootstrap(monthValue:unknown){const r=monthBounds(monthValue);const ctx=await context(r.start);const[{data:master,error:me},{data:schedules,error:se},{data:teachers,error:te}]=await Promise.all([sb.from("saturday_activity_master").select("id,code,name,requires_certificate,sort_order,is_active").eq("is_active",true).order("sort_order").order("name"),sb.from("teacher_saturday_schedule").select("id,event_date,activity_master_id,activity_name,start_time,end_time,note,audience_mode,is_active,updated_at,saturday_activity_master(id,code,name,requires_certificate)").eq("academic_year_id",ctx.yearId).eq("semester_no",ctx.semesterNo).eq("is_active",true).gte("event_date",r.start).lte("event_date",r.end).order("event_date"),sb.from("teachers").select("id,full_name,status,position,teacher_code").order("full_name")]);if(me)throw me;if(se)throw se;if(te)throw te;const activeTeachers=(teachers||[]).filter((x:any)=>!["nonaktif","inactive","disabled"].includes(L(x.status))&&L(x.position)!=="hrd"&&L(x.teacher_code)!=="hrd001");const ids=(schedules||[]).map((x:any)=>x.id);const{data:parts,error:pe}=ids.length?await sb.from("teacher_saturday_participants").select("saturday_schedule_id,teacher_id,is_assigned,attendance_status,start_time,end_time,note").in("saturday_schedule_id",ids):{data:[],error:null};if(pe)throw pe;const out=(schedules||[]).map((s:any)=>{const ps=(parts||[]).filter((p:any)=>p.saturday_schedule_id===s.id&&p.is_assigned!==false);const m=Array.isArray(s.saturday_activity_master)?s.saturday_activity_master[0]:s.saturday_activity_master;return{...s,activity_name:m?.name||s.activity_name||"Kegiatan Sabtu",requires_certificate:!!m?.requires_certificate,participant_rows:ps.length,attendance_filled:ps.filter((p:any)=>T(p.attendance_status)).length,teacher_count:activeTeachers.length}});return{success:true,month:r.month,academic_year:ctx.yearName,semester_no:ctx.semesterNo,master:master||[],schedules:out,teacher_count:activeTeachers.length}}
async function save(me:any,b:any){const date=T(b.event_date),mid=T(b.activity_master_id),start=T(b.start_time||"08:00"),end=T(b.end_time||"10:00"),note=T(b.note);if(!isSaturday(date)||!mid||mins(start)===null||mins(end)===null||Number(mins(end))<=Number(mins(start)))throw Error("invalid_input");const{data:m}=await sb.from("saturday_activity_master").select("id,name,is_active").eq("id",mid).maybeSingle();if(!m||!m.is_active)throw Error("activity_invalid");const ctx=await context(date);const row={school_unit_id:ctx.unitId,academic_year_id:ctx.yearId,semester_no:ctx.semesterNo,event_date:date,activity_master_id:mid,activity_name:m.name,start_time:start,end_time:end,note:note||null,audience_mode:"all_teachers",is_active:true,created_by_account_id:me.id,updated_at:new Date().toISOString()};const{data,error}=await sb.from("teacher_saturday_schedule").upsert(row,{onConflict:"academic_year_id,semester_no,event_date"}).select("*").single();if(error)throw error;return{success:true,row:data}}
async function remove(b:any){const id=T(b.id);if(!id)throw Error("id_required");const{error}=await sb.from("teacher_saturday_schedule").update({is_active:false,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;return{success:true}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return J({success:false,error:"method_not_allowed"},405);try{const me=await auth(req);if(!me)return J({success:false,error:"forbidden"},403);const b=await req.json().catch(()=>({})),action=L(b.action||"bootstrap");if(action==="bootstrap")return J(await bootstrap(b.month));if(action==="save")return J(await save(me,b));if(action==="delete")return J(await remove(b));return J({success:false,error:"unknown_action"},400)}catch(e){console.error("hrd-saturday-schedule",e);const m=T((e as any)?.message)||"server_error";return J({success:false,error:m},m==="forbidden"?403:400)}});