/* CQlass — Raw Ekskul: Admin intake -> review Kabid Kegiatan */
(function(){
  'use strict';
  if(window.__cqExtracurricularRawUI) return;
  const BASE=(typeof SUPABASE_URL!=='undefined'?SUPABASE_URL:'https://lmglkxzemtvxcgktiord.supabase.co')+'/functions/v1/extracurricular-raw';
  const A={rows:[],counts:{},academic_year:'',semester_no:1};
  const K={rows:[],counts:{},extracurriculars:[],filter:'pending'};
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const role=()=>String(window.currentUser?.role||'').toLowerCase();
  const toast=(m,e)=>typeof showToast==='function'?showToast(m,!!e):alert(m);
  async function api(action,p={}){
    const token=typeof getAuthToken==='function'?getAuthToken():localStorage.getItem('cqlass_session_token');
    const key=typeof SUPABASE_PUBLISHABLE_KEY!=='undefined'?SUPABASE_PUBLISHABLE_KEY:'';
    const r=await fetch(BASE,{method:'POST',headers:{'Content-Type':'application/json','apikey':key,'Authorization':'Bearer '+key,'x-session-token':token||''},body:JSON.stringify({action,...p})});
    const d=await r.json().catch(()=>({}));
    if(!r.ok||d.success===false){
      const map={admin_only:'Menu ini hanya untuk Admin.',kegiatan_only:'Menu ini hanya untuk Kabid Kegiatan.',session_invalid:'Sesi login sudah tidak valid.',rows_empty:'Belum ada data raw yang diisi.',no_valid_rows:'Tidak ada baris raw yang valid.',too_many_rows:'Maksimal 1.500 baris sekali simpan.',mapping_required:'Pilih ekskul resmi terlebih dahulu.',raw_not_editable:'Baris ini sudah diproses dan tidak dapat diubah.',extracurricular_not_found:'Ekskul resmi tidak ditemukan.'};
      throw new Error(d.detail||map[d.error]||d.error||'Data raw ekskul belum dapat diproses.');
    }
    return d;
  }
  function css(){if(document.getElementById('cq-raw-ex-css'))return;const s=document.createElement('style');s.id='cq-raw-ex-css';s.textContent=`
  .rx{max-width:1480px;margin:auto;color:#173b39}.rx-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;flex-wrap:wrap;margin-bottom:13px}.rx-head h2{margin:0;font-size:24px;letter-spacing:-.4px}.rx-head p{margin:4px 0 0;font-size:10px;color:var(--muted);line-height:1.5}.rx-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:#edf7f6;color:#08746f;font-size:8px;font-weight:900}.rx-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:11px}.rx-kpi,.rx-card{background:#fff;border:1px solid var(--border);border-radius:13px;padding:12px}.rx-kpi b{display:block;font-size:21px;color:#0b6561}.rx-kpi span{font-size:8.5px;color:var(--muted)}.rx-card h3{font-size:12px;margin:0 0 8px}.rx-note{font-size:9px;color:var(--muted);line-height:1.5}.rx-area{width:100%;min-height:210px;resize:vertical;border:1px solid #b9cfcd;border-radius:10px;padding:10px;font:500 10px/1.55 Inter,system-ui;background:#fff;box-sizing:border-box}.rx-row{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.rx-in,.rx-sel{height:36px;border:1px solid #b9cfcd;border-radius:8px;background:#fff;padding:0 8px;font:inherit;font-size:9px}.rx-in{min-width:220px}.rx-btn{border:1px solid var(--border);background:#fff;border-radius:8px;padding:8px 10px;font-size:8.5px;font-weight:900;cursor:pointer}.rx-btn.primary{background:#08746f;color:#fff;border-color:#08746f}.rx-btn.danger{color:#a64234}.rx-btn:disabled{opacity:.5;cursor:not-allowed}.rx-tablewrap{overflow:auto;border:1px solid var(--border);border-radius:10px}.rx-table{width:100%;border-collapse:collapse;min-width:1080px}.rx-table th,.rx-table td{padding:7px 8px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top;font-size:8.5px}.rx-table th{background:#f5f9f8;text-transform:uppercase;color:var(--muted);font-size:7.5px}.rx-table .rx-edit{width:100%;min-width:120px;height:31px;border:1px solid #d0dddc;border-radius:7px;padding:0 6px;font:inherit;font-size:8.5px;box-sizing:border-box}.rx-status{display:inline-flex;padding:4px 6px;border-radius:999px;font-size:7.5px;font-weight:900}.rx-status.pending{background:#eef6ff;color:#376b9a}.rx-status.issue{background:#fff1df;color:#98620d}.rx-status.applied{background:#e9f7ee;color:#347452}.rx-status.ignored{background:#f1f2f2;color:#687270}.rx-actions{display:flex;gap:4px;flex-wrap:wrap;min-width:180px}.rx-toolbar{display:flex;gap:7px;align-items:center;justify-content:space-between;flex-wrap:wrap;margin-bottom:8px}.rx-empty{padding:22px;text-align:center;color:var(--muted);font-size:9px}.rx-warn{padding:9px 10px;border-radius:9px;background:#fff7e8;color:#7b5b1d;font-size:9px;line-height:1.5;margin-bottom:10px}.rx-ok{padding:9px 10px;border-radius:9px;background:#edf8f3;color:#306d50;font-size:9px;line-height:1.5;margin-bottom:10px}@media(max-width:800px){.rx-grid{grid-template-columns:repeat(2,1fr)}.rx-head h2{font-size:20px}.rx-in{min-width:160px}}
  `;document.head.appendChild(s)}
  function statusLabel(s){return {pending:'Menunggu',issue:'Perlu Koreksi',applied:'Sudah Diterapkan',ignored:'Diabaikan'}[s]||s}
  function kpis(c){return `<div class="rx-grid"><div class="rx-kpi"><b>${Number(c.pending||0)}</b><span>Menunggu Kabid</span></div><div class="rx-kpi"><b>${Number(c.issue||0)}</b><span>Perlu Koreksi</span></div><div class="rx-kpi"><b>${Number(c.applied||0)}</b><span>Sudah Diterapkan</span></div><div class="rx-kpi"><b>${Number(c.total||0)}</b><span>Total Raw</span></div></div>`}
  function parseRaw(text){
    const lines=String(text||'').split(/\r?\n/).map(x=>x.trimEnd()).filter(x=>x.trim());if(!lines.length)return[];
    const sample=lines[0],delim=sample.includes('\t')?'\t':sample.includes('|')?'|':sample.includes(';')?';':',';
    const split=l=>l.split(delim).map(x=>x.trim().replace(/^"|"$/g,''));
    let rows=lines.map(split);const h=rows[0].map(x=>x.toLowerCase());if(h.some(x=>/ekskul|extrakurikuler|pelatih|nama siswa|kelas/.test(x)))rows=rows.slice(1);
    return rows.map((x,i)=>({extracurricular_name:x[0]||'',coach_name:x[1]||'',group_label:x[2]||'',student_name:x[3]||'',class_name:x[4]||'',source_ref:x[5]||`Admin raw baris ${i+1}`})).filter(x=>x.extracurricular_name);
  }
  async function adminLoad(){const d=await api('admin_list');A.rows=d.rows||[];A.counts=d.counts||{};A.academic_year=d.academic_year||'';A.semester_no=d.semester_no||1;return d}
  function adminTable(){const rows=A.rows||[];if(!rows.length)return '<div class="rx-empty">Belum ada raw ekskul dari Admin.</div>';return `<div class="rx-tablewrap"><table class="rx-table"><thead><tr><th>Ekskul Raw</th><th>Pelatih</th><th>Kelompok</th><th>Siswa</th><th>Kelas</th><th>Status</th><th>Catatan Kabid</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.extracurricular_name)}</b></td><td>${esc(r.coach_name||'—')}</td><td>${esc(r.group_label||'—')}</td><td>${esc(r.student_name||'—')}</td><td>${esc(r.class_name||'—')}</td><td><span class="rx-status ${esc(r.status)}">${esc(statusLabel(r.status))}</span></td><td>${esc(r.issue_detail||'—')}</td><td>${['pending','issue'].includes(r.status)?`<button class="rx-btn danger" onclick="cqRawAdminDelete('${esc(r.id)}')">Hapus</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
  function renderAdmin(content){css();content.innerHTML=`<div class="rx"><div class="rx-head"><div><h2>Input Raw Ekskul</h2><p>Admin hanya memasukkan data mentah. Pemilik dan pengesahan data tetap Kabid Kegiatan.</p></div><span class="rx-badge">Admin → Kabid Kegiatan</span></div>${kpis(A.counts)}<div class="rx-warn"><b>Belum masuk rapor.</b> Data yang disimpan di sini menjadi antrean Kabid Kegiatan. Kabid harus mengecek nama ekskul, pelatih, siswa, dan kelas sebelum diterapkan ke master ekskul.</div><div class="rx-card"><h3>Paste Data dari Excel / Spreadsheet</h3><div class="rx-note">Urutan kolom: <b>Ekskul | Pelatih | Kelompok/Jadwal | Nama Siswa | Kelas | Sumber (opsional)</b>. Bisa paste langsung dari Excel karena tab otomatis terbaca.</div><textarea id="rx-admin-area" class="rx-area" placeholder="Contoh:\nPublic Speaking\tKa Diva\tKelompok A\tAhmad Fulan\t4A Banin\nArabic Club\tUst. Faris\tKelompok 1\tAli Hasan\t5A Banin"></textarea><div class="rx-row"><button class="rx-btn primary" onclick="cqRawAdminSave()">Kirim ke Kabid Kegiatan</button><button class="rx-btn" onclick="document.getElementById('rx-admin-area').value=''">Kosongkan</button><span class="rx-note">Tahun ${esc(A.academic_year)} · Semester ${esc(A.semester_no)}</span></div></div><div class="rx-card" style="margin-top:10px"><div class="rx-toolbar"><div><h3 style="margin:0">Riwayat Raw Ekskul</h3><div class="rx-note">Status berubah otomatis setelah diproses Kabid Kegiatan.</div></div><button class="rx-btn" onclick="cqRawAdminRefresh()">Muat Ulang</button></div>${adminTable()}</div></div>`}
  window.renderAdminRawEkskul=async function(content){content.innerHTML='<div class="rx"><div class="rx-card">Memuat raw ekskul...</div></div>';try{await adminLoad();renderAdmin(content)}catch(e){content.innerHTML='<div class="rx"><div class="rx-card rx-empty">'+esc(e.message)+'</div></div>'}};
  window.cqRawAdminSave=async function(){const area=document.getElementById('rx-admin-area'),rows=parseRaw(area?.value||'');if(!rows.length){toast('Belum ada baris raw ekskul yang valid.',true);return}if(!confirm(`Kirim ${rows.length} baris raw ke Kabid Kegiatan?`))return;try{const d=await api('admin_save',{rows});toast(`${d.inserted||rows.length} baris raw berhasil dikirim ke Kabid Kegiatan.`);area.value='';await adminLoad();renderAdmin(document.getElementById('content'))}catch(e){toast(e.message,true)}};
  window.cqRawAdminDelete=async function(id){if(!confirm('Hapus baris raw ini?'))return;try{await api('admin_delete',{id});toast('Baris raw dihapus.');await adminLoad();renderAdmin(document.getElementById('content'))}catch(e){toast(e.message,true)}};
  window.cqRawAdminRefresh=async function(){try{await adminLoad();renderAdmin(document.getElementById('content'))}catch(e){toast(e.message,true)}};

  async function kegiatanLoad(){const d=await api('kegiatan_list');K.rows=d.rows||[];K.counts=d.counts||{};K.extracurriculars=d.extracurriculars||[];return d}
  function exOptions(selected){return `<option value="">Pilih ekskul resmi...</option>${K.extracurriculars.map(x=>`<option value="${esc(x.id)}" ${selected===x.id?'selected':''}>${esc(x.name)}${x.quota!=null?' · kuota '+x.quota:''}</option>`).join('')}`}
  function filtered(){return K.filter==='all'?K.rows:K.rows.filter(r=>r.status===K.filter)}
  function kegiatanTable(){const rows=filtered();if(!rows.length)return '<div class="rx-empty">Tidak ada raw ekskul pada status ini.</div>';return `<div class="rx-tablewrap"><table class="rx-table"><thead><tr><th>Ekskul Raw</th><th>Pelatih</th><th>Kelompok</th><th>Siswa</th><th>Kelas</th><th>Ekskul Resmi</th><th>Status / Masalah</th><th>Tindakan</th></tr></thead><tbody>${rows.map(r=>{const editable=['pending','issue'].includes(r.status);return `<tr><td><input class="rx-edit" id="rx-ex-${r.id}" value="${esc(r.extracurricular_name)}" ${editable?'':'disabled'}></td><td><input class="rx-edit" id="rx-coach-${r.id}" value="${esc(r.coach_name||'')}" ${editable?'':'disabled'}></td><td><input class="rx-edit" id="rx-group-${r.id}" value="${esc(r.group_label||'')}" ${editable?'':'disabled'}></td><td><input class="rx-edit" id="rx-student-${r.id}" value="${esc(r.student_name||'')}" ${editable?'':'disabled'}></td><td><input class="rx-edit" id="rx-class-${r.id}" value="${esc(r.class_name||'')}" ${editable?'':'disabled'}></td><td><select class="rx-edit" id="rx-target-${r.id}" ${editable?'':'disabled'}>${exOptions(r.matched_extracurricular_id||'')}</select></td><td><span class="rx-status ${esc(r.status)}">${esc(statusLabel(r.status))}</span>${r.issue_detail?`<div class="rx-note" style="color:#98620d">${esc(r.issue_detail)}</div>`:''}</td><td>${editable?`<div class="rx-actions"><button class="rx-btn" onclick="cqRawKegiatanSave('${r.id}')">Simpan Koreksi</button><button class="rx-btn primary" onclick="cqRawKegiatanApply('${r.id}')">Terapkan</button><button class="rx-btn" onclick="cqRawKegiatanApplyName('${r.id}')">Terapkan Nama Ini</button><button class="rx-btn danger" onclick="cqRawKegiatanIgnore('${r.id}')">Abaikan</button></div>`:'—'}</td></tr>`}).join('')}</tbody></table></div>`}
  function renderKegiatan(content){css();content.innerHTML=`<div class="rx"><div class="rx-head"><div><h2>Raw Ekskul dari Admin</h2><p>Validasi data mentah sebelum masuk ke data ekskul resmi dan digunakan untuk proses rapor.</p></div><span class="rx-badge">Pemilik Data: Kabid Kegiatan</span></div>${kpis(K.counts)}<div class="rx-ok"><b>Alur aman:</b> Admin mengirim raw → Kabid mengoreksi → pilih Ekskul Resmi → Terapkan. Hanya baris berstatus <b>Sudah Diterapkan</b> yang masuk ke keanggotaan ekskul resmi.</div><div class="rx-card"><div class="rx-toolbar"><div class="rx-row" style="margin-top:0"><select class="rx-sel" onchange="cqRawKegiatanFilter(this.value)"><option value="pending" ${K.filter==='pending'?'selected':''}>Menunggu</option><option value="issue" ${K.filter==='issue'?'selected':''}>Perlu Koreksi</option><option value="applied" ${K.filter==='applied'?'selected':''}>Sudah Diterapkan</option><option value="ignored" ${K.filter==='ignored'?'selected':''}>Diabaikan</option><option value="all" ${K.filter==='all'?'selected':''}>Semua</option></select><span class="rx-note">${filtered().length} baris tampil</span></div><button class="rx-btn" onclick="cqRawKegiatanRefresh()">Muat Ulang</button></div>${kegiatanTable()}</div></div>`}
  window.renderKegiatanRawEkskul=async function(content){content.innerHTML='<div class="rx"><div class="rx-card">Memuat raw ekskul dari Admin...</div></div>';try{await kegiatanLoad();renderKegiatan(content)}catch(e){content.innerHTML='<div class="rx"><div class="rx-card rx-empty">'+esc(e.message)+'</div></div>'}};
  function val(id){return document.getElementById(id)?.value||''}
  window.cqRawKegiatanFilter=function(v){K.filter=v;renderKegiatan(document.getElementById('content'))};
  window.cqRawKegiatanRefresh=async function(){try{await kegiatanLoad();renderKegiatan(document.getElementById('content'))}catch(e){toast(e.message,true)}};
  window.cqRawKegiatanSave=async function(id){try{await api('kegiatan_update',{id,extracurricular_name:val('rx-ex-'+id),coach_name:val('rx-coach-'+id),group_label:val('rx-group-'+id),student_name:val('rx-student-'+id),class_name:val('rx-class-'+id)});toast('Koreksi raw ekskul disimpan.');await kegiatanLoad();renderKegiatan(document.getElementById('content'))}catch(e){toast(e.message,true)}};
  window.cqRawKegiatanApply=async function(id){const target=val('rx-target-'+id);if(!target){toast('Pilih Ekskul Resmi terlebih dahulu.',true);return}try{await api('kegiatan_update',{id,extracurricular_name:val('rx-ex-'+id),coach_name:val('rx-coach-'+id),group_label:val('rx-group-'+id),student_name:val('rx-student-'+id),class_name:val('rx-class-'+id)});await api('kegiatan_apply',{id,extracurricular_id:target});toast('Raw ekskul berhasil diterapkan ke data resmi.');await kegiatanLoad();renderKegiatan(document.getElementById('content'))}catch(e){toast(e.message,true);await kegiatanLoad();renderKegiatan(document.getElementById('content'))}};
  window.cqRawKegiatanApplyName=async function(id){const raw=val('rx-ex-'+id),target=val('rx-target-'+id);if(!target){toast('Pilih Ekskul Resmi terlebih dahulu.',true);return}const ex=K.extracurriculars.find(x=>x.id===target);if(!confirm(`Terapkan semua baris raw bernama “${raw}” ke ekskul resmi “${ex?.name||''}”?`))return;try{const d=await api('kegiatan_apply_name',{raw_name:raw,extracurricular_id:target});toast(`${d.applied||0} baris diterapkan; ${d.issues||0} perlu koreksi.`);await kegiatanLoad();renderKegiatan(document.getElementById('content'))}catch(e){toast(e.message,true)}};
  window.cqRawKegiatanIgnore=async function(id){if(!confirm('Abaikan baris raw ini?'))return;try{await api('kegiatan_ignore',{id});toast('Baris raw diabaikan.');await kegiatanLoad();renderKegiatan(document.getElementById('content'))}catch(e){toast(e.message,true)}};

  function bind(){
    try{
      if(typeof MODULE_GROUPS==='undefined'||!Array.isArray(MODULE_GROUPS))return false;
      let adm=MODULE_GROUPS.find(g=>g&&g.id==='administrasi');if(!adm){adm={id:'administrasi',label:'Administrasi',roles:['admin'],items:[]};MODULE_GROUPS.push(adm)}
      adm.roles=Array.from(new Set([...(adm.roles||[]),'admin']));adm.items=adm.items||[];
      let ai=adm.items.find(x=>x&&x.id==='admin-raw-ekskul');if(!ai){adm.items.push({id:'admin-raw-ekskul',label:'Raw Ekskul',roles:['admin'],built:true,render:window.renderAdminRawEkskul})}else{ai.roles=['admin'];ai.built=true;ai.render=window.renderAdminRawEkskul}
      let info=MODULE_GROUPS.find(g=>g&&g.id==='info');if(!info){info={id:'info',label:'Info',roles:['kegiatan'],items:[]};MODULE_GROUPS.push(info)}
      info.roles=Array.from(new Set([...(info.roles||[]),'kegiatan']));info.items=info.items||[];
      let ki=info.items.find(x=>x&&x.id==='kegiatan-raw-ekskul');if(!ki){info.items.push({id:'kegiatan-raw-ekskul',label:'Raw Ekskul Admin',roles:['kegiatan'],built:true,render:window.renderKegiatanRawEkskul})}else{ki.roles=['kegiatan'];ki.built=true;ki.render=window.renderKegiatanRawEkskul}
      return true;
    }catch(e){console.warn('Bind Raw Ekskul:',e);return false}
  }
  bind();setTimeout(()=>{if(bind()&&typeof renderSidebar==='function'&&['admin','kegiatan'].includes(role()))renderSidebar()},300);setTimeout(()=>{if(bind()&&typeof renderSidebar==='function'&&['admin','kegiatan'].includes(role()))renderSidebar()},1200);
  window.__cqExtracurricularRawUI=true;
})();
