/* CQlass — Raw Ekskul: Admin import/export Excel -> review Kabid Kegiatan */
(function(){
  'use strict';
  const URL=SUPABASE_URL+'/functions/v1/extracurricular-raw';
  const state={adminRows:[],kegiatanRows:[],counts:{},extras:[]};
  const esc=v=>escapeHtml(String(v==null?'':v));
  async function api(action,payload={}){const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_PUBLISHABLE_KEY,'Authorization':'Bearer '+SUPABASE_PUBLISHABLE_KEY,'x-session-token':getAuthToken()},body:JSON.stringify({action,...payload})});let d={};try{d=JSON.parse(await r.text()||'{}')}catch(_){throw Error('Respons Raw Ekskul tidak valid.')}if(!r.ok||d.success===false){const m={admin_only:'Menu ini khusus Admin.',kegiatan_only:'Menu ini khusus Kabid Kegiatan.',rows_empty:'Tidak ada baris yang dapat diimport.',no_valid_rows:'Tidak ada baris valid. Pastikan Nama Ekskul terisi.',too_many_rows:'Maksimal 1500 baris per import.',raw_not_editable:'Data sudah diproses dan tidak dapat diedit lagi.',apply_issue:d.detail||'Data perlu dikoreksi sebelum diterapkan.'};throw Error(m[d.error]||d.error||'Proses Raw Ekskul gagal.')}return d}
  function inject(){if(document.getElementById('raw-ex-style-v2'))return;const s=document.createElement('style');s.id='raw-ex-style-v2';s.textContent=`.rx-wrap{max-width:1250px;margin:auto}.rx-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:12px}.rx-head h2{margin:0;font-size:24px}.rx-head p{font-size:10px;color:var(--muted);line-height:1.5;max-width:820px}.rx-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.rx-kpi{background:#fff;border:1px solid var(--border);border-radius:13px;padding:10px}.rx-kpi b{display:block;font-size:22px;color:#075b59}.rx-kpi span{font-size:8.5px;color:var(--muted);font-weight:800}.rx-card{background:#fff;border:1px solid var(--border);border-radius:15px;padding:13px;margin-bottom:10px}.rx-actions{display:flex;gap:7px;flex-wrap:wrap}.rx-drop{border:1px dashed #9fc8c4;border-radius:12px;padding:14px;background:#f8fcfb}.rx-drop input[type=file]{max-width:100%}.rx-paste{width:100%;min-height:115px;box-sizing:border-box}.rx-tablewrap{overflow:auto;max-height:52vh;border:1px solid var(--border);border-radius:11px}.rx-table{width:100%;border-collapse:collapse;min-width:1050px}.rx-table th,.rx-table td{padding:8px;border-bottom:1px solid #edf1f2;font-size:9px;text-align:left;vertical-align:top}.rx-table th{position:sticky;top:0;background:#f7fafb;z-index:1}.rx-status{display:inline-flex;padding:3px 6px;border-radius:999px;font-size:8px;font-weight:850}.rx-status.pending{background:#fff4dc;color:#8c6509}.rx-status.issue{background:#fff0ec;color:#a14431}.rx-status.applied{background:#e8f7ef;color:#2e7350}.rx-status.ignored{background:#eef1f3;color:#68727a}.rx-edit{width:100%;min-width:120px}.rx-note{font-size:8.5px;color:var(--muted);line-height:1.4}.rx-map{min-width:180px}@media(max-width:760px){.rx-grid{grid-template-columns:repeat(2,1fr)}.rx-head{flex-direction:column}}`;document.head.appendChild(s)}
  async function xlsx(){if(window.XLSX)return window.XLSX;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=resolve;s.onerror=()=>reject(Error('Library Excel gagal dimuat.'));document.head.appendChild(s)});return window.XLSX}
  function norm(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ')}
  function mapObject(o){const m={};Object.keys(o||{}).forEach(k=>m[norm(k)]=o[k]);const pick=(...ks)=>{for(const k of ks)if(m[k]!==undefined&&String(m[k]).trim()!=='')return String(m[k]).trim();return''};return{extracurricular_name:pick('nama ekskul','ekskul','jenis ekskul'),coach_name:pick('nama pelatih','pelatih'),group_label:pick('kelompok jadwal','kelompok','grup','group'),student_name:pick('nama siswa','siswa'),class_name:pick('kelas','class'),source_ref:pick('sumber','source','source ref')}}
  async function parseFile(file){const X=await xlsx(),buf=await file.arrayBuffer(),wb=X.read(buf,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],raw=X.utils.sheet_to_json(ws,{defval:''});return raw.map(mapObject).filter(r=>r.extracurricular_name)}
  function parsePaste(v){const lines=String(v||'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const delim=lines[0].includes('\t')?'\t':lines[0].includes('|')?'|':lines[0].includes(';')?';':',';const cells=l=>l.split(delim).map(x=>x.trim());let start=0;const h=cells(lines[0]).map(norm);if(h.some(x=>x.includes('ekskul')))start=1;return lines.slice(start).map(l=>{const c=cells(l);return{extracurricular_name:c[0]||'',coach_name:c[1]||'',group_label:c[2]||'',student_name:c[3]||'',class_name:c[4]||'',source_ref:c[5]||''}}).filter(r=>r.extracurricular_name)}
  async function exportRows(rows,name){const X=await xlsx(),data=(rows||[]).map(r=>({'Nama Ekskul':r.extracurricular_name||'','Nama Pelatih':r.coach_name||'','Kelompok / Jadwal':r.group_label||'','Nama Siswa':r.student_name||'','Kelas':r.class_name||'','Sumber':r.source_ref||'','Status Sistem':r.status||'','Catatan Masalah':r.issue_detail||''})),ws=X.utils.json_to_sheet(data.length?data:[{'Nama Ekskul':'','Nama Pelatih':'','Kelompok / Jadwal':'','Nama Siswa':'','Kelas':'','Sumber':''}]),wb=X.utils.book_new();ws['!cols']=[{wch:24},{wch:22},{wch:24},{wch:28},{wch:16},{wch:20},{wch:15},{wch:38}];X.utils.book_append_sheet(wb,ws,'Peserta Ekskul');X.writeFile(wb,name)}
  function kpis(c){return`<div class="rx-grid"><div class="rx-kpi"><b>${c.pending||0}</b><span>Menunggu Kabid</span></div><div class="rx-kpi"><b>${c.issue||0}</b><span>Perlu Koreksi</span></div><div class="rx-kpi"><b>${c.applied||0}</b><span>Sudah Diterapkan</span></div><div class="rx-kpi"><b>${c.total||0}</b><span>Total Raw</span></div></div>`}
  async function loadAdmin(){const d=await api('admin_list');state.adminRows=d.rows||[];state.counts=d.counts||{};return d}
  async function renderAdmin(content){inject();content.innerHTML='<div class="rx-wrap"><div class="rx-card"><span class="spinner"></span> Memuat Raw Ekskul...</div></div>';try{const d=await loadAdmin();content.innerHTML=`<div class="rx-wrap"><div class="rx-head"><div><h2>Input Raw Ekskul</h2><p>Admin hanya memasukkan data mentahan. Setelah masuk, pengelolaan peserta—edit, tambah, pindah ekskul/grup, eksternal, dan tidak mengikuti—menjadi kewenangan Kabid Kegiatan.</p></div><div class="rx-actions"><button class="kv2-btn secondary" onclick="rxTemplate()">Download Format Excel</button><button class="kv2-btn ghost" onclick="rxExportAdmin()">Export Data Raw</button></div></div>${kpis(d.counts||{})}<div class="rx-card"><div class="kv2-title">Import Excel</div><div class="rx-drop" style="margin-top:8px"><input id="rx-file" type="file" accept=".xlsx,.xls,.csv"><div class="rx-note" style="margin-top:7px">Kolom yang dibaca: Nama Ekskul, Nama Pelatih, Kelompok/Jadwal, Nama Siswa, Kelas, Sumber. Kolom lain boleh ada dan akan diabaikan.</div></div><div class="rx-actions" style="margin-top:9px"><button class="kv2-btn" onclick="rxImportFile()">Import Excel ke Raw</button></div></div><div class="rx-card"><details><summary style="cursor:pointer;font-weight:850;font-size:10px">Atau paste langsung dari Excel/Spreadsheet</summary><textarea id="rx-paste" class="kv2-input rx-paste" style="margin-top:9px" placeholder="Nama Ekskul | Nama Pelatih | Kelompok/Jadwal | Nama Siswa | Kelas | Sumber"></textarea><div class="rx-actions" style="margin-top:8px"><button class="kv2-btn secondary" onclick="rxImportPaste()">Kirim Paste ke Raw</button></div></details></div><div class="rx-card"><div class="kv2-title">Riwayat Raw</div><div class="rx-tablewrap" style="margin-top:8px"><table class="rx-table"><thead><tr><th>Ekskul</th><th>Pelatih</th><th>Kelompok</th><th>Siswa</th><th>Kelas</th><th>Status</th><th>Catatan</th><th>Aksi</th></tr></thead><tbody>${state.adminRows.length?state.adminRows.map(r=>`<tr><td>${esc(r.extracurricular_name)}</td><td>${esc(r.coach_name||'-')}</td><td>${esc(r.group_label||'-')}</td><td>${esc(r.student_name||'-')}</td><td>${esc(r.class_name||'-')}</td><td><span class="rx-status ${esc(r.status)}">${esc(r.status)}</span></td><td>${esc(r.issue_detail||'')}</td><td>${['pending','issue'].includes(r.status)?`<button class="kv2-btn ghost" onclick="rxDelete('${r.id}')">Hapus</button>`:'-'}</td></tr>`).join(''):'<tr><td colspan="8" style="text-align:center;padding:24px">Belum ada data raw.</td></tr>'}</tbody></table></div></div></div>`}catch(e){content.innerHTML='<div class="rx-wrap"><div class="rx-card">'+esc(e.message)+'</div></div>'}}
  window.rxImportFile=async function(){const f=document.getElementById('rx-file')?.files?.[0];if(!f){showToast('Pilih file Excel terlebih dahulu.',true);return}try{const rows=await parseFile(f);if(!rows.length){showToast('Tidak ada baris valid pada file.',true);return}const d=await api('admin_save',{rows});showToast(`${d.inserted||rows.length} baris raw berhasil diimport.`);await renderAdmin(document.getElementById('content'))}catch(e){showToast(e.message||'Import gagal.',true)}}
  window.rxImportPaste=async function(){const rows=parsePaste(document.getElementById('rx-paste')?.value||'');if(!rows.length){showToast('Paste data belum terbaca.',true);return}try{const d=await api('admin_save',{rows});showToast(`${d.inserted||rows.length} baris raw berhasil masuk.`);await renderAdmin(document.getElementById('content'))}catch(e){showToast(e.message,true)}}
  window.rxTemplate=async function(){await exportRows([],`Format_Import_Ekskul_CQlass.xlsx`)}
  window.rxExportAdmin=async function(){await exportRows(state.adminRows,`Export_Raw_Ekskul_CQlass.xlsx`)}
  window.rxDelete=async function(id){if(!confirm('Hapus baris raw ini?'))return;try{await api('admin_delete',{id});showToast('Baris raw dihapus.');await renderAdmin(document.getElementById('content'))}catch(e){showToast(e.message,true)}}

  async function renderKegiatan(content){inject();content.innerHTML='<div class="rx-wrap"><div class="rx-card"><span class="spinner"></span> Memuat Raw Ekskul Admin...</div></div>';try{const d=await api('kegiatan_list');state.kegiatanRows=d.rows||[];state.counts=d.counts||{};state.extras=d.extracurriculars||[];const opts='<option value="">Pilih ekskul resmi...</option>'+state.extras.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');content.innerHTML=`<div class="rx-wrap"><div class="rx-head"><div><h2>Raw Ekskul dari Admin</h2><p>Ini kotak masuk data mentahan. Koreksi dan terapkan ke data resmi; setelah diterapkan, perubahan harian peserta dilakukan di menu Data Ekskul Siswa.</p></div></div>${kpis(d.counts||{})}<div class="rx-card"><div class="rx-tablewrap"><table class="rx-table"><thead><tr><th>Ekskul Raw</th><th>Pelatih</th><th>Kelompok</th><th>Siswa</th><th>Kelas</th><th>Ekskul Resmi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${state.kegiatanRows.length?state.kegiatanRows.map(r=>`<tr><td><input id="re-${r.id}" class="kv2-input rx-edit" value="${esc(r.extracurricular_name)}"></td><td><input id="rp-${r.id}" class="kv2-input rx-edit" value="${esc(r.coach_name||'')}"></td><td><input id="rg-${r.id}" class="kv2-input rx-edit" value="${esc(r.group_label||'')}"></td><td><input id="rs-${r.id}" class="kv2-input rx-edit" value="${esc(r.student_name||'')}"></td><td><input id="rc-${r.id}" class="kv2-input rx-edit" value="${esc(r.class_name||'')}"></td><td><select id="rm-${r.id}" class="kv2-select rx-map">${opts}</select>${r.issue_detail?`<div class="rx-note" style="color:#a14431">${esc(r.issue_detail)}</div>`:''}</td><td><span class="rx-status ${esc(r.status)}">${esc(r.status)}</span></td><td>${['pending','issue'].includes(r.status)?`<div class="rx-actions"><button class="kv2-btn secondary" onclick="rxSaveRaw('${r.id}')">Simpan Koreksi</button><button class="kv2-btn" onclick="rxApply('${r.id}')">Terapkan</button><button class="kv2-btn ghost" onclick="rxIgnore('${r.id}')">Abaikan</button></div>`:'-'}</td></tr>`).join(''):'<tr><td colspan="8" style="text-align:center;padding:24px">Tidak ada data raw.</td></tr>'}</tbody></table></div></div></div>`}catch(e){content.innerHTML='<div class="rx-wrap"><div class="rx-card">'+esc(e.message)+'</div></div>'}}
  window.rxSaveRaw=async function(id){try{await api('kegiatan_update',{id,extracurricular_name:document.getElementById('re-'+id)?.value||'',coach_name:document.getElementById('rp-'+id)?.value||'',group_label:document.getElementById('rg-'+id)?.value||'',student_name:document.getElementById('rs-'+id)?.value||'',class_name:document.getElementById('rc-'+id)?.value||''});showToast('Koreksi raw disimpan.');await renderKegiatan(document.getElementById('content'))}catch(e){showToast(e.message,true)}}
  window.rxApply=async function(id){const ex=document.getElementById('rm-'+id)?.value||'';if(!ex){showToast('Pilih ekskul resmi terlebih dahulu.',true);return}try{await api('kegiatan_update',{id,extracurricular_name:document.getElementById('re-'+id)?.value||'',coach_name:document.getElementById('rp-'+id)?.value||'',group_label:document.getElementById('rg-'+id)?.value||'',student_name:document.getElementById('rs-'+id)?.value||'',class_name:document.getElementById('rc-'+id)?.value||''});await api('kegiatan_apply',{id,extracurricular_id:ex});showToast('Data diterapkan ke Data Ekskul resmi.');await renderKegiatan(document.getElementById('content'))}catch(e){showToast(e.message,true)}}
  window.rxIgnore=async function(id){if(!confirm('Abaikan data raw ini?'))return;try{await api('kegiatan_ignore',{id});showToast('Data raw diabaikan.');await renderKegiatan(document.getElementById('content'))}catch(e){showToast(e.message,true)}}

  window.renderAdminRawEkskul=renderAdmin;window.renderKegiatanRawEkskul=renderKegiatan;
  function bind(){try{if(typeof MODULE_GROUPS!=='undefined'){let adminGroup=MODULE_GROUPS.find(g=>String(g.id||g.label||'').toLowerCase().includes('admin'))||MODULE_GROUPS.find(g=>(g.items||[]).some(i=>i.roles?.includes('admin')));if(adminGroup&&!adminGroup.items.some(i=>i.id==='admin-raw-ekskul'))adminGroup.items.push({id:'admin-raw-ekskul',label:'Raw Ekskul',roles:['admin'],built:true,render:renderAdmin});let info=MODULE_GROUPS.find(g=>g.id==='info')||MODULE_GROUPS.find(g=>String(g.label||'').toLowerCase()==='info');if(info&&!info.items.some(i=>i.id==='kegiatan-raw-ekskul'))info.items.push({id:'kegiatan-raw-ekskul',label:'Raw Ekskul Admin',roles:['kegiatan','kabid_kegiatan'],built:true,render:renderKegiatan})}}catch(e){console.warn('Bind Raw Ekskul gagal',e)}}bind();setTimeout(bind,900);setTimeout(bind,2500);
})();