/* CQlass — Laporan Sarpras & Saran/Masukan */
(function(){'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function role(){return String((window.currentUser&&currentUser.role)||window.CURRENT_ROLE||'').toLowerCase()}
 function accountId(){return (window.currentUser&&(currentUser.account_id||currentUser.user_account_id||currentUser.id))||null}
 function allowedReporter(){return ['walas','wali_kelas','guru_partner','partner','tahfizh','guru'].includes(role())}
 function handler(){return ['sapras','kabid_kesiswaan','kesiswaan'].includes(role())}
 async function api(method,query,body){let u=SUPABASE_URL+'/rest/v1/internal_reports'+(query||'');let r=await fetch(u,{method,headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.status===204?[]:r.json()}
 async function compress(file){return new Promise((ok,no)=>{let im=new Image(),fr=new FileReader();fr.onload=e=>{im.onload=()=>{let s=Math.min(1,1600/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.78))};im.onerror=no;im.src=e.target.result};fr.onerror=no;fr.readAsDataURL(file)})}
 function form(){return `<div class="rd-card"><div class="rd-card-title">Laporan & Masukan</div><div class="rd-card-sub">Sarpras diteruskan ke Tim Sapras. Saran/masukan lainnya diteruskan ke Kesiswaan.</div><form id="ir-form" style="display:grid;gap:12px;margin-top:16px"><label>Jenis<select id="ir-type" required><option value="SAPRAS">Sarana & Prasarana</option><option value="SARAN_MASUKAN">Saran & Masukan</option></select></label><label id="ir-loc-wrap">Lokasi / Ruangan<input id="ir-location" placeholder="Contoh: Kelas 3A"></label><label>Deskripsi detail<textarea id="ir-desc" rows="4" required></textarea></label><label>Saran / tindakan yang diinginkan<textarea id="ir-action" rows="3" required></textarea></label><label>Foto <span id="ir-photo-required">(wajib untuk Sarpras)</span><input id="ir-photo" type="file" accept="image/*"></label><img id="ir-preview" style="display:none;max-width:260px;border-radius:12px"><button class="btn" type="submit">Kirim Laporan</button></form></div><div id="ir-list" style="margin-top:16px"></div>`}
 function handlerView(){return `<div class="rd-card"><div class="rd-card-title">${role()==='sapras'?'Laporan Sarpras':'Saran & Masukan'}</div><div class="rd-card-sub">Buka laporan, proses, lalu berikan bukti penyelesaian.</div></div><div id="ir-list" style="margin-top:16px"></div>`}
 async function load(){let id=accountId(),q='?select=*&order=created_at.desc';if(role()==='sapras')q+='&report_type=eq.SAPRAS';else if(['kabid_kesiswaan','kesiswaan'].includes(role()))q+='&report_type=eq.SARAN_MASUKAN';else if(id)q+='&reporter_account_id=eq.'+encodeURIComponent(id);let rows=await api('GET',q);let el=document.getElementById('ir-list');if(!el)return;el.innerHTML=rows.length?rows.map(card).join(''):'<div class="rd-card">Belum ada laporan.</div>'}
 function card(x){let can=handler();return `<div class="rd-card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(x.ticket_no||x.report_type)}</b><span>${esc(x.status)}</span></div><small>${new Date(x.created_at).toLocaleString('id-ID')}</small>${x.location?`<p><b>Lokasi:</b> ${esc(x.location)}</p>`:''}<p>${esc(x.description)}</p><p><b>Saran:</b> ${esc(x.requested_action)}</p>${x.photo_url?`<img src="${esc(x.photo_url)}" style="max-width:240px;border-radius:12px">`:''}${x.resolution_note?`<p><b>Tindak lanjut:</b> ${esc(x.resolution_note)}</p>`:''}${x.resolution_photo_url?`<img src="${esc(x.resolution_photo_url)}" style="max-width:240px;border-radius:12px">`:''}${can?`<div style="display:grid;gap:8px;margin-top:12px"><select id="st-${x.id}"><option>DILAPORKAN</option><option>DIPROSES</option><option>SELESAI</option><option>TIDAK_DITINDAKLANJUTI</option></select><textarea id="nt-${x.id}" placeholder="Catatan tindak lanjut">${esc(x.resolution_note||'')}</textarea><input id="ph-${x.id}" type="file" accept="image/*"><button class="btn" onclick="window.irResolve('${x.id}')">Simpan Tindak Lanjut</button></div>`:''}</div>`}
 window.irResolve=async id=>{try{let st=document.getElementById('st-'+id).value,n=document.getElementById('nt-'+id).value.trim(),f=document.getElementById('ph-'+id).files[0],p=f?await compress(f):null;if(st==='SELESAI'&&!p)throw Error('Foto/bukti penyelesaian wajib saat status Selesai.');await api('PATCH','?id=eq.'+id,{status:st,resolution_note:n,resolution_photo_url:p||undefined,resolved_at:st==='SELESAI'?new Date().toISOString():null,updated_at:new Date().toISOString()});load()}catch(e){alert(e.message)}};
 window.renderInternalReports=function(){let c=document.getElementById('content');if(!c)return;c.innerHTML=handler()?handlerView():form();let type=document.getElementById('ir-type'),photo=document.getElementById('ir-photo'),preview=document.getElementById('ir-preview');if(photo)photo.onchange=async()=>{if(photo.files[0]){preview.src=await compress(photo.files[0]);preview.style.display='block'}};let f=document.getElementById('ir-form');if(f)f.onsubmit=async e=>{e.preventDefault();try{let t=type.value,p=photo.files[0];if(t==='SAPRAS'&&!p)throw Error('Foto wajib untuk laporan Sarpras.');let img=p?await compress(p):null;await api('POST','',{report_type:t,reporter_account_id:accountId(),location:document.getElementById('ir-location').value.trim(),description:document.getElementById('ir-desc').value.trim(),requested_action:document.getElementById('ir-action').value.trim(),photo_url:img});f.reset();preview.style.display='none';load()}catch(x){alert(x.message)}};load()};
 function inject(){let sb=document.getElementById('sidebar');if(!sb||(!allowedReporter()&&!handler()))return;if(sb.querySelector('[data-ir-menu]'))return;let b=document.createElement('button');b.dataset.irMenu='1';b.className='menu-item';b.innerHTML='<span>🛠️</span><span>'+(role()==='sapras'?'Laporan Sarpras':'Laporan & Masukan')+'</span>';b.onclick=window.renderInternalReports;sb.appendChild(b)}
 new MutationObserver(inject).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('DOMContentLoaded',inject);setTimeout(inject,1200);
})();