/* CQlass — Kepala Sekolah: Jurnal, RKT, RKJM, Agenda Harian, Laporan Kinerja */
(function(){
  const KEPSEK_WORK_URL=`${SUPABASE_URL}/functions/v1/kepsek-work`;
  const KS_YEAR='2026/2027';
  const KS_CFG={
    journal:{title:'Jurnal Kepala Sekolah',sub:'Catatan kegiatan, hasil, dan tindak lanjut kepala sekolah.',icon:'book',fields:[
      ['entry_date','Tanggal','date',true],['start_time','Waktu','time'],['activity_type','Jenis Kegiatan','text'],['title','Kegiatan / Agenda','text',true],['description','Uraian Kegiatan','textarea'],['parties','Pihak yang Terlibat','text'],['result','Hasil Kegiatan','textarea'],['follow_up','Tindak Lanjut','textarea'],['follow_up_status','Status Tindak Lanjut','select',['belum','proses','selesai']],['evidence_url','Tautan Dokumentasi','text']
    ]},
    rkt:{title:'RKT (Rencana Kerja Tahunan)',sub:'Program kerja satu tahun dan progres pelaksanaannya.',icon:'target',fields:[
      ['academic_year','Tahun Pelajaran','text',true],['field','Bidang','text'],['program_name','Program Kerja','text',true],['target','Sasaran / Target','textarea'],['success_indicator','Indikator Keberhasilan','textarea'],['planned_start','Mulai','date'],['planned_end','Selesai','date'],['responsible_person','Penanggung Jawab','text'],['budget','Anggaran','number'],['progress_percent','Progres (%)','number'],['status','Status','select',['belum','proses','selesai','tertunda']],['realization_note','Realisasi','textarea'],['evaluation','Evaluasi','textarea'],['follow_up','Tindak Lanjut','textarea'],['evidence_url','Tautan Bukti','text']
    ]},
    rkjm:{title:'RKJM (Rencana Kerja Jangka Menengah)',sub:'Sasaran strategis sekolah untuk empat tahun.',icon:'trend',fields:[
      ['period_start_year','Tahun Mulai','number',true],['period_end_year','Tahun Selesai','number',true],['strategic_area','Bidang Strategis','text'],['strategic_goal','Sasaran Strategis','textarea',true],['baseline','Kondisi Awal','textarea'],['year1_target','Target Tahun 1','textarea'],['year2_target','Target Tahun 2','textarea'],['year3_target','Target Tahun 3','textarea'],['year4_target','Target Tahun 4','textarea'],['current_progress','Kondisi / Capaian Saat Ini','textarea'],['progress_percent','Progres (%)','number'],['status','Status','select',['belum','proses','selesai','tertunda']],['evaluation','Evaluasi','textarea'],['follow_up','Tindak Lanjut','textarea']
    ]},
    daily:{title:'Rencana Kerja Harian',sub:'Agenda dan pekerjaan kepala sekolah setiap hari.',icon:'calendar',fields:[
      ['plan_date','Tanggal','date',true],['start_time','Mulai','time'],['end_time','Selesai','time'],['title','Agenda / Pekerjaan','text',true],['priority','Prioritas','select',['rendah','normal','tinggi']],['related_parties','Pihak Terkait','text'],['location','Lokasi','text'],['status','Status','select',['belum','proses','selesai','tertunda']],['notes','Catatan','textarea'],['follow_up','Tindak Lanjut','textarea']
    ]}
  };
  let ksState={section:'journal',rows:[],edit:null,period:'month'};

  function ksToday(){return typeof jakartaTodayISO==='function'?jakartaTodayISO():new Date().toISOString().slice(0,10)}
  function ksIcon(name,size=22){
    const a=`width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"`;
    const m={book:`<svg ${a}><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M4 4v15.5"/><path d="M20 22V6a2 2 0 0 0-2-2H6.5A2.5 2.5 0 0 0 4 6.5"/></svg>`,target:`<svg ${a}><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></svg>`,trend:`<svg ${a}><path d="M3 17l6-6 4 4 8-9"/><path d="M15 6h6v6"/></svg>`,calendar:`<svg ${a}><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/><path d="m9 15 2 2 4-4"/></svg>`,report:`<svg ${a}><path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></svg>`,edit:`<svg ${a}><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg>`,trash:`<svg ${a}><path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6"/></svg>`};return m[name]||m.report;
  }
  function ksStyles(){if(document.getElementById('ks-work-style'))return;const s=document.createElement('style');s.id='ks-work-style';s.textContent=`
    .ks-wrap{max-width:1320px;margin:0 auto}.ks-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap;margin-bottom:14px}
    .ks-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ks-card{background:#fff;border:1px solid var(--border);border-radius:17px;padding:17px}
    .ks-menu{display:grid;grid-template-columns:1fr;gap:11px;max-width:760px}.ks-menu-card{display:grid;grid-template-columns:74px 1fr 28px;align-items:center;gap:16px;padding:20px;border:1px solid var(--border);border-radius:18px;background:#fff;cursor:pointer;text-align:left;transition:.15s}.ks-menu-card:hover{transform:translateY(-1px);box-shadow:0 8px 24px rgba(20,60,58,.08)}.ks-menu-icon{width:64px;height:64px;border-radius:17px;display:flex;align-items:center;justify-content:center;color:#fff}.ks-menu-card:nth-child(1) .ks-menu-icon{background:#347ff1}.ks-menu-card:nth-child(2) .ks-menu-icon{background:#18b964}.ks-menu-card:nth-child(3) .ks-menu-icon{background:#9a39eb}.ks-menu-card:nth-child(4) .ks-menu-icon{background:#16aaa0}.ks-menu-card:nth-child(5) .ks-menu-icon{background:#ef3159}.ks-menu-title{font-size:17px;font-weight:900;color:var(--text)}.ks-menu-sub{font-size:12px;color:var(--muted);margin-top:4px}.ks-menu-stat{font-size:12px;color:#2570d7;font-weight:850;margin-top:8px}.ks-chevron{font-size:30px;color:#b5c2c1}
    .ks-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ks-field.full{grid-column:1/-1}.ks-field label{display:block;font-size:10.5px;font-weight:900;color:var(--muted);text-transform:uppercase;letter-spacing:.03em;margin-bottom:6px}.ks-field input,.ks-field select,.ks-field textarea{width:100%;border:1.5px solid var(--border);border-radius:10px;padding:10px 11px;background:#fff;font:inherit;color:var(--text);outline:none}.ks-field textarea{min-height:86px;resize:vertical}.ks-field input:focus,.ks-field select:focus,.ks-field textarea:focus{border-color:var(--primary);box-shadow:0 0 0 3px rgba(10,110,110,.08)}
    .ks-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin-top:13px}.ks-table-wrap{overflow:auto;border:1px solid var(--border);border-radius:12px}.ks-table{width:100%;border-collapse:collapse;min-width:850px}.ks-table th,.ks-table td{padding:9px 10px;border-bottom:1px solid var(--border);font-size:11px;text-align:left;vertical-align:top}.ks-table th{background:#f4f9f9;color:var(--muted);font-size:9.5px;text-transform:uppercase}.ks-table tr:last-child td{border-bottom:0}.ks-mini{border:1px solid var(--border);background:#fff;border-radius:8px;padding:6px;cursor:pointer;color:var(--text);margin-right:4px}.ks-pill{display:inline-flex;padding:4px 8px;border-radius:999px;background:#eef7f6;color:#176f69;font-size:9.5px;font-weight:900}.ks-pill.selesai{background:#e8f7ee;color:#367550}.ks-pill.tertunda{background:#fff0ec;color:#a84c3b}
    .ks-kpis{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px;margin:12px 0}.ks-kpi{background:#fff;border:1px solid var(--border);border-radius:14px;padding:14px}.ks-kpi strong{display:block;font-size:24px;color:#075f5d}.ks-kpi span{font-size:10px;color:var(--muted);font-weight:800}.ks-report-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.ks-report-card{background:#fff;border:1px solid var(--border);border-radius:14px;padding:14px}.ks-report-card b{font-size:10px;color:var(--muted);text-transform:uppercase}.ks-report-card strong{display:block;font-size:24px;color:#075f5d;margin-top:6px}.ks-progress{height:8px;background:#eaf0ef;border-radius:999px;margin-top:9px;overflow:hidden}.ks-progress i{display:block;height:100%;background:#0b7d79;border-radius:999px}.ks-toolbar{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.ks-period{display:flex;gap:5px;flex-wrap:wrap}.ks-period button{border:1px solid var(--border);background:#fff;border-radius:9px;padding:7px 10px;font:inherit;font-size:10px;font-weight:800;cursor:pointer}.ks-period button.active{background:var(--primary);color:#fff;border-color:var(--primary)}
    @media(max-width:850px){.ks-grid,.ks-form-grid,.ks-report-grid{grid-template-columns:1fr}.ks-kpis{grid-template-columns:repeat(2,1fr)}.ks-menu-card{grid-template-columns:58px 1fr 18px;padding:15px}.ks-menu-icon{width:52px;height:52px}.ks-menu-title{font-size:14px}}
    @media print{body *{visibility:hidden!important}#ks-print,#ks-print *{visibility:visible!important}#ks-print{position:absolute;left:0;top:0;width:100%;padding:20px}.sidebar,.topbar{display:none!important}}
  `;document.head.appendChild(s)}

  async function ksReq(action,payload={}){const token=getAuthToken();if(!token)throw new Error('Sesi login tidak ditemukan.');const r=await fetch(KEPSEK_WORK_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'x-session-token':token},body:JSON.stringify({action,...payload})});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{throw new Error('Respons modul Kepala Sekolah tidak valid.')}if(!r.ok||d.success===false){const m={forbidden:'Menu ini khusus Kepala Sekolah.',session_invalid:'Sesi login sudah berakhir.',invalid_section:'Bagian data tidak valid.'};throw new Error(m[d.error]||d.message||d.error||'Gagal memproses data.')}return d}

  function ksDefault(section,key){if(key==='entry_date'||key==='plan_date')return ksToday();if(key==='academic_year')return KS_YEAR;if(key==='period_start_year')return 2026;if(key==='period_end_year')return 2030;if(key==='progress_percent')return 0;if(key==='follow_up_status'||key==='status')return'belum';if(key==='priority')return'normal';return''}
  function ksFieldHtml(section,f,row){const [key,label,type,req]=f;const val=row?.[key]??ksDefault(section,key);const full=type==='textarea'?' full':'';let input='';if(type==='textarea')input=`<textarea id="ksf-${key}" ${req?'required':''}>${escapeHtml(val)}</textarea>`;else if(type==='select'){const opts=f[3]||[];input=`<select id="ksf-${key}">${opts.map(x=>`<option value="${escapeHtml(x)}" ${String(val)===String(x)?'selected':''}>${escapeHtml(String(x).replace(/^./,c=>c.toUpperCase()))}</option>`).join('')}</select>`}else input=`<input id="ksf-${key}" type="${type}" value="${escapeHtml(val)}" ${type==='number'&&key==='progress_percent'?'min="0" max="100" step="1"':''} ${req?'required':''}>`;return `<div class="ks-field${full}"><label>${escapeHtml(label)}</label>${input}</div>`}
  function ksCollect(section){const o={};for(const f of KS_CFG[section].fields){const el=document.getElementById(`ksf-${f[0]}`);if(!el)continue;let v=el.value;if(f[2]==='number')v=v===''?null:Number(v);o[f[0]]=v}return o}

  async function ksRenderSection(content,section){ksStyles();ksState.section=section;ksState.edit=null;const cfg=KS_CFG[section];content.innerHTML=`<div class="ks-wrap"><div class="ks-head"><div><div class="page-title">${cfg.title}</div><div class="page-sub">${cfg.sub}</div></div><button class="btn btn-sm" onclick="ksShowForm('${section}')">+ Tambah Data</button></div><div id="ks-form-area"></div><div id="ks-list-area"><div class="card"><span class="spinner"></span> Memuat data...</div></div></div>`;await ksLoadList(section)}
  window.ksShowForm=function(section,id=''){const row=id?ksState.rows.find(x=>String(x.id)===String(id)):null;ksState.edit=row||null;const area=document.getElementById('ks-form-area');if(!area)return;const cfg=KS_CFG[section];area.innerHTML=`<div class="card"><div class="card-title">${row?'Edit':'Tambah'} ${cfg.title}</div><div class="ks-form-grid">${cfg.fields.map(f=>ksFieldHtml(section,f,row)).join('')}</div><div class="ks-actions"><button class="btn btn-secondary" onclick="document.getElementById('ks-form-area').innerHTML=''">Batal</button><button class="btn" id="ks-save" onclick="ksSave('${section}')">Simpan</button></div></div>`;area.scrollIntoView({behavior:'smooth',block:'start'})}
  window.ksSave=async function(section){const data=ksCollect(section);const req=KS_CFG[section].fields.find(f=>f[3]===true&&(!data[f[0]]&&data[f[0]]!==0));if(req){showToast(`${req[1]} wajib diisi.`,true);return}const btn=document.getElementById('ks-save');if(btn){btn.disabled=true;btn.innerHTML='<span class="spinner"></span>Menyimpan...'}try{await ksReq('save',{section,id:ksState.edit?.id||'',data});showToast('Data berhasil disimpan.');document.getElementById('ks-form-area').innerHTML='';ksState.edit=null;await ksLoadList(section)}catch(e){showToast(e.message||'Gagal menyimpan.',true)}finally{if(btn){btn.disabled=false;btn.textContent='Simpan'}}}
  window.ksDelete=async function(section,id){if(!confirm('Hapus data ini?'))return;try{await ksReq('delete',{section,id});showToast('Data dihapus.');await ksLoadList(section)}catch(e){showToast(e.message||'Gagal menghapus.',true)}}

  function ksRowSummary(section,r){if(section==='journal')return [r.entry_date,r.title,r.activity_type||'-',r.follow_up_status];if(section==='rkt')return [r.field||'-',r.program_name,`${Number(r.progress_percent||0)}%`,r.status];if(section==='rkjm')return [`${r.period_start_year}–${r.period_end_year}`,r.strategic_goal,`${Number(r.progress_percent||0)}%`,r.status];return [r.plan_date,r.title,r.start_time?String(r.start_time).slice(0,5):'-',r.status]}
  function ksListHeaders(section){return section==='journal'?['Tanggal','Kegiatan','Jenis','Status']:section==='rkt'?['Bidang','Program','Progres','Status']:section==='rkjm'?['Periode','Sasaran Strategis','Progres','Status']:['Tanggal','Agenda','Waktu','Status']}
  async function ksLoadList(section){const area=document.getElementById('ks-list-area');if(!area)return;try{const d=await ksReq('list',{section,academic_year:section==='rkt'?KS_YEAR:undefined,limit:150});ksState.rows=d.data||[];if(!ksState.rows.length){area.innerHTML='<div class="card"><div class="rd-empty">Belum ada data. Klik “Tambah Data” untuk mulai.</div></div>';return}const hs=ksListHeaders(section);area.innerHTML=`<div class="card"><div class="card-title">Data Tersimpan</div><div class="ks-table-wrap"><table class="ks-table"><thead><tr>${hs.map(x=>`<th>${x}</th>`).join('')}<th>Aksi</th></tr></thead><tbody>${ksState.rows.map(r=>{const a=ksRowSummary(section,r);const st=String(a[3]||'');return `<tr>${a.slice(0,3).map(v=>`<td>${escapeHtml(v??'-')}</td>`).join('')}<td><span class="ks-pill ${escapeHtml(st)}">${escapeHtml(st)}</span></td><td><button class="ks-mini" title="Edit" onclick="ksShowForm('${section}','${escapeHtml(r.id)}')">${ksIcon('edit',14)}</button><button class="ks-mini" title="Hapus" onclick="ksDelete('${section}','${escapeHtml(r.id)}')">${ksIcon('trash',14)}</button></td></tr>`}).join('')}</tbody></table></div></div>`}catch(e){area.innerHTML=`<div class="card"><div class="ms-alert">${escapeHtml(e.message||'Gagal memuat data.')}</div></div>`}}

  window.renderKepsekJurnal=c=>ksRenderSection(c,'journal');
  window.renderKepsekRKT=c=>ksRenderSection(c,'rkt');
  window.renderKepsekRKJM=c=>ksRenderSection(c,'rkjm');
  window.renderKepsekHarian=c=>ksRenderSection(c,'daily');

  function pct(v){return v==null?'—':`${Number(v).toLocaleString('id-ID',{maximumFractionDigits:1})}%`}
  function num(v){return v==null?'—':Number(v).toLocaleString('id-ID',{maximumFractionDigits:1})}
  function ksReportCard(label,value,sub=''){return `<div class="ks-report-card"><b>${escapeHtml(label)}</b><strong>${escapeHtml(value)}</strong><span style="font-size:10px;color:var(--muted)">${escapeHtml(sub)}</span></div>`}
  window.ksSetPeriod=async function(p){ksState.period=p;await ksLoadReport()}
  window.renderKepsekLaporan=function(content){ksStyles();ksState.period='month';content.innerHTML=`<div class="ks-wrap"><div class="ks-head"><div><div class="page-title">Laporan Kinerja Kepala Sekolah</div><div class="page-sub">Ringkasan otomatis dari seluruh data CQlass + program kerja Kepala Sekolah.</div></div></div><div id="ks-report-root"></div></div>`;ksLoadReport()}
  window.ksLoadReport=async function(){const root=document.getElementById('ks-report-root');if(!root)return;root.innerHTML='<div class="card"><span class="spinner"></span> Menyusun laporan kinerja...</div>';try{const [w,d]=await Promise.all([ksReq('summary',{academic_year:KS_YEAR}),roleDashboardRequest('dashboard',{period:ksState.period})]);const x=w.summary||{},s=d.summary||{},a=d.academic||{},di=d.discipline||{},t=d.tahfizh||{},ex=d.extracurricular||{},pj=d.pjbl||{};root.innerHTML=`<div id="ks-print"><div class="card"><div class="ks-toolbar"><div><div class="card-title">Periode Laporan</div><div class="page-sub">${escapeHtml(d.period?.start||'')} s.d. ${escapeHtml(d.period?.end||'')}</div></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><div class="ks-period">${[['month','Bulanan'],['quarter','Triwulan'],['semester','Semester'],['year','Tahunan']].map(q=>`<button class="${ksState.period===q[0]?'active':''}" onclick="ksSetPeriod('${q[0]}')">${q[1]}</button>`).join('')}</div><button class="btn btn-sm" onclick="window.print()">Cetak / PDF</button></div></div></div>
      <div class="ks-kpis">${ksReportCard('Jurnal Bulan Ini',String(x.journal_month||0),'kegiatan tercatat')}${ksReportCard('Progres RKT',pct(x.rkt_progress),`${x.rkt_done||0}/${x.rkt_total||0} selesai`)}${ksReportCard('Agenda Hari Ini',`${x.daily_done||0}/${x.daily_today||0}`,'selesai / total')}${ksReportCard('Progres RKJM',pct(x.rkjm_progress),`${x.rkjm_total||0} sasaran`)}</div>
      <div class="card"><div class="card-title">Kondisi Sekolah — Otomatis dari CQlass</div><div class="ks-report-grid" style="margin-top:12px">${ksReportCard('Kehadiran Siswa',pct(s.attendance_pct),'periode terpilih')}${ksReportCard('Rata-rata Akademik',num(s.academic_avg),`${num(s.academic_score_count)} data nilai`)}${ksReportCard('Nilai di Bawah 75',pct(a.below_75_pct),'perlu perhatian')}${ksReportCard('Tahfizh Terisi',pct(t.completion_pct),`${num(t.filled)} / ${num(t.total)} data`)}${ksReportCard('Pelanggaran',num(di.incidents),`${num(di.points)} poin`)}${ksReportCard('Reward',num(di.rewards),`${num(di.reward_points)} poin`)}${ksReportCard('PjBL',num(pj.logs||s.pjbl_logs),`${num(pj.classes||s.pjbl_classes)} kelas aktif`)}${ksReportCard('Pertemuan Ekskul',num(ex.sessions||s.extracurricular_sessions),`${num(ex.assessments||s.extracurricular_assessments)} penilaian`)}${ksReportCard('Kasus Perlu Penanganan',num(s.escalation_count||di.cases),'monitoring kesiswaan')}</div></div>
      <div class="ks-grid" style="margin-top:12px"><div class="card"><div class="card-title">Jurnal Terakhir</div>${(x.journal_latest||[]).length?(x.journal_latest||[]).map((q:any)=>`<div style="padding:9px 0;border-bottom:1px solid var(--border)"><b style="font-size:11px">${escapeHtml(q.title||'-')}</b><div style="font-size:10px;color:var(--muted)">${escapeHtml(q.entry_date||'')} · ${escapeHtml(q.follow_up_status||'')}</div></div>`).join(''):'<div class="rd-empty">Belum ada jurnal bulan ini.</div>'}</div><div class="card"><div class="card-title">Agenda Hari Ini</div>${(x.daily_items||[]).length?(x.daily_items||[]).map((q:any)=>`<div style="padding:9px 0;border-bottom:1px solid var(--border)"><b style="font-size:11px">${escapeHtml(q.title||'-')}</b><div style="font-size:10px;color:var(--muted)">${escapeHtml(String(q.start_time||'').slice(0,5)||'-')} · ${escapeHtml(q.status||'')}</div></div>`).join(''):'<div class="rd-empty">Belum ada agenda hari ini.</div>'}</div></div></div>`}catch(e){root.innerHTML=`<div class="card"><div class="ms-alert">${escapeHtml(e.message||'Gagal menyusun laporan kinerja.')}</div></div>`}}

  window.renderKepsekHome=async function(content){ksStyles();content.innerHTML=`<div class="ks-wrap"><div class="page-title">Ruang Kerja Kepala Sekolah</div><div class="page-sub">Jurnal, rencana kerja, agenda, dan laporan kinerja dalam satu tempat.</div><div id="ks-home" style="margin-top:16px"><div class="card"><span class="spinner"></span> Memuat ringkasan...</div></div></div>`;try{const d=await ksReq('summary',{academic_year:KS_YEAR}),x=d.summary||{};const root=document.getElementById('ks-home');if(!root)return;root.innerHTML=`<div class="ks-menu">
    <button class="ks-menu-card" onclick="setActiveModule('kepsek-jurnal')"><span class="ks-menu-icon">${ksIcon('book',30)}</span><span><span class="ks-menu-title">Jurnal Kepala Sekolah</span><span class="ks-menu-sub">Catatan kegiatan harian kepsek</span><span class="ks-menu-stat">${x.journal_month||0} entri bulan ini</span></span><span class="ks-chevron">›</span></button>
    <button class="ks-menu-card" onclick="setActiveModule('kepsek-rkt')"><span class="ks-menu-icon">${ksIcon('target',30)}</span><span><span class="ks-menu-title">RKT (Rencana Kerja Tahunan)</span><span class="ks-menu-sub">Program kerja 1 tahun</span><span class="ks-menu-stat">Progres ${pct(x.rkt_progress)}</span></span><span class="ks-chevron">›</span></button>
    <button class="ks-menu-card" onclick="setActiveModule('kepsek-rkjm')"><span class="ks-menu-icon">${ksIcon('trend',30)}</span><span><span class="ks-menu-title">RKJM (Rencana Kerja Jangka Menengah)</span><span class="ks-menu-sub">Rencana strategis 4 tahun</span><span class="ks-menu-stat">${x.rkjm_total||0} sasaran strategis</span></span><span class="ks-chevron">›</span></button>
    <button class="ks-menu-card" onclick="setActiveModule('kepsek-harian')"><span class="ks-menu-icon">${ksIcon('calendar',30)}</span><span><span class="ks-menu-title">Rencana Kerja Harian</span><span class="ks-menu-sub">Agenda harian kepala sekolah</span><span class="ks-menu-stat">${x.daily_today||0} agenda hari ini</span></span><span class="ks-chevron">›</span></button>
    <button class="ks-menu-card" onclick="setActiveModule('kepsek-laporan')"><span class="ks-menu-icon">${ksIcon('report',30)}</span><span><span class="ks-menu-title">Laporan Kinerja</span><span class="ks-menu-sub">Rekap otomatis seluruh indikator sekolah</span><span class="ks-menu-stat">Siap dilihat & dicetak</span></span><span class="ks-chevron">›</span></button></div>`}catch(e){document.getElementById('ks-home').innerHTML=`<div class="card"><div class="ms-alert">${escapeHtml(e.message||'Gagal memuat ruang kerja.')}</div></div>`}}

  try{
    if(!MODULE_GROUPS.some(g=>g.id==='kepsek'))MODULE_GROUPS.push({id:'kepsek',label:'Kepala Sekolah',roles:['pimpinan'],items:[
      {id:'kepsek-home',label:'Ruang Kerja Kepsek',roles:['pimpinan'],built:true,render:renderKepsekHome},
      {id:'kepsek-jurnal',label:'Jurnal Kepala Sekolah',roles:['pimpinan'],built:true,render:renderKepsekJurnal},
      {id:'kepsek-rkt',label:'RKT',roles:['pimpinan'],built:true,render:renderKepsekRKT},
      {id:'kepsek-rkjm',label:'RKJM',roles:['pimpinan'],built:true,render:renderKepsekRKJM},
      {id:'kepsek-harian',label:'Rencana Kerja Harian',roles:['pimpinan'],built:true,render:renderKepsekHarian},
      {id:'kepsek-laporan',label:'Laporan Kinerja',roles:['pimpinan'],built:true,render:renderKepsekLaporan}
    ]});
  }catch(e){console.error('Kepsek module bind gagal',e)}
})();
