/* CQlass — Bukti Promosi untuk seluruh role */
(function(){
  'use strict';
  const API=SUPABASE_URL+'/functions/v1/hrd-live-report';
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const monthStart=()=>today().slice(0,8)+'01';
  async function api(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_PUBLISHABLE_KEY,'Authorization':'Bearer '+SUPABASE_PUBLISHABLE_KEY,'x-session-token':getAuthToken()},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.error==='image_too_large'?'Foto maksimal 2 MB.':d.message||d.error||'Gagal menyimpan laporan promosi.');return d}
  function css(){if(document.getElementById('promo-report-style'))return;const s=document.createElement('style');s.id='promo-report-style';s.textContent=`.pr-shell{display:grid;gap:15px}.pr-hero{padding:22px;border-radius:22px;background:linear-gradient(135deg,#064a4a,#0a6e6e);color:#fff}.pr-hero h1{margin:4px 0 6px;font-size:25px}.pr-hero p{margin:0;opacity:.82;font-size:13px}.pr-grid{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(0,1.2fr);gap:15px}.pr-card{background:#fff;border:1px solid var(--border,#dce8e7);border-radius:18px;padding:17px;box-shadow:0 7px 24px rgba(13,72,72,.06)}.pr-card h2{font-size:16px;margin:0 0 4px}.pr-card>p{font-size:11px;color:var(--muted,#6b8080);margin:0 0 15px}.pr-form{display:grid;gap:11px}.pr-form label{display:grid;gap:5px;font-size:11px;font-weight:800;color:#375454}.pr-form input,.pr-form textarea{width:100%;box-sizing:border-box;border:1px solid #d4e4e2;border-radius:11px;padding:10px 11px;font:inherit;background:#fbfdfd}.pr-form button{border:0;border-radius:11px;padding:11px;background:#0a6e6e;color:#fff;font-weight:850;cursor:pointer}.pr-preview{display:none;width:100%;max-height:240px;object-fit:cover;border-radius:13px}.pr-status{padding:10px 12px;border-radius:12px;font-size:11px;font-weight:800}.pr-status.ok{background:#e8f7ef;color:#177145}.pr-status.bad{background:#fff2f1;color:#a04039}.pr-list{display:grid;gap:10px}.pr-item{display:grid;grid-template-columns:90px 1fr auto;gap:12px;align-items:center;border:1px solid #dce9e8;border-radius:14px;padding:10px}.pr-item img{width:90px;height:70px;object-fit:cover;border-radius:10px}.pr-item b{display:block;font-size:12px}.pr-item span,.pr-item small{display:block;color:#6d8383;font-size:10px;margin-top:4px}.pr-delete{border:0;background:#fdeceb;color:#a43d36;border-radius:9px;padding:8px;font-weight:800;cursor:pointer}@media(max-width:760px){.pr-grid{grid-template-columns:1fr}.pr-item{grid-template-columns:74px 1fr}.pr-item img{width:74px;height:62px}.pr-delete{grid-column:1/-1}}`;document.head.appendChild(s)}
  async function compress(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.82))}catch(e){reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Foto tidak dapat dibaca.'))};img.src=url})}
  async function load(){const box=document.getElementById('pr-list');if(!box)return;box.innerHTML='<div class="empty-state">Memuat bukti promosi...</div>';try{const d=await api({action:'my',start:monthStart(),end:today()}),status=document.getElementById('pr-status');status.className='pr-status '+(d.fulfilled?'ok':'bad');status.textContent=d.fulfilled?'✓ Kewajiban bulan ini sudah terpenuhi.':'Belum memenuhi: unggah minimal 1 foto promosi bulan ini.';box.innerHTML=(d.items||[]).length?(d.items||[]).map(x=>`<article class="pr-item"><a href="${esc(x.photo_url)}" target="_blank" rel="noopener"><img src="${esc(x.photo_url)}" alt="Bukti promosi"></a><div><b>${esc(x.title)}</b><span>${esc(x.description||'Tanpa keterangan')}</span><small>${esc(x.activity_date)}</small></div><button class="pr-delete" onclick="deletePromotionReport('${esc(x.id)}')">Hapus</button></article>`).join(''):'<div class="empty-state">Belum ada foto promosi pada bulan ini.</div>'}catch(e){box.innerHTML='<div class="empty-state">'+esc(e.message)+'</div>'}}
  function render(){css();const c=document.getElementById('content');if(!c)return;c.innerHTML=`<div class="pr-shell"><section class="pr-hero"><small>LAPORAN BULANAN</small><h1>Bukti Promosi Sekolah</h1><p>Setiap pegawai wajib mengunggah minimal satu foto promosi pada periode laporan.</p></section><div class="pr-grid"><section class="pr-card"><h2>Tambah Bukti</h2><p>Satu kegiatan menggunakan satu foto yang jelas.</p><div id="pr-status" class="pr-status bad">Memeriksa status...</div><form class="pr-form" id="pr-form" style="margin-top:12px"><label>Tanggal kegiatan<input id="pr-date" type="date" value="${today()}" required></label><label>Judul kegiatan<input id="pr-title" maxlength="120" value="Promosi Sekolah" required></label><label>Keterangan singkat<textarea id="pr-desc" rows="3" maxlength="500" placeholder="Contoh: Membagikan informasi PPDB melalui status WhatsApp"></textarea></label><label>Foto promosi (wajib)<input id="pr-file" type="file" accept="image/jpeg,image/png,image/webp" required></label><img id="pr-preview" class="pr-preview" alt="Pratinjau foto"><button id="pr-save" type="submit">Simpan Foto Promosi</button></form></section><section class="pr-card"><h2>Riwayat Bulan Ini</h2><p>Foto yang tersimpan otomatis masuk ke Live Report HRD.</p><div id="pr-list" class="pr-list"></div></section></div></div>`;let encoded='';document.getElementById('pr-file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;encoded=await compress(f);const p=document.getElementById('pr-preview');p.src=encoded;p.style.display='block'};document.getElementById('pr-form').onsubmit=async e=>{e.preventDefault();if(!encoded)return showToast('Pilih foto promosi terlebih dahulu.',true);const b=document.getElementById('pr-save');b.disabled=true;b.textContent='Menyimpan...';try{await api({action:'upload',activity_date:document.getElementById('pr-date').value,title:document.getElementById('pr-title').value,description:document.getElementById('pr-desc').value,mime_type:'image/jpeg',base64:encoded});showToast('Foto promosi berhasil masuk ke Live Report HRD.');render()}catch(err){showToast(err.message,true);b.disabled=false;b.textContent='Simpan Foto Promosi'}};load()}
  async function remove(id){if(!confirm('Hapus foto promosi ini?'))return;try{await api({action:'delete',id});showToast('Foto promosi dihapus.');load()}catch(e){showToast(e.message,true)}}
  const PROMO_ROLES=['guru','walas','admin','hrd','pimpinan','kepsek','akademik','kesiswaan','tahfizh','kegiatan','sapras','guru_partner','kabid_akademik','kabid_kesiswaan','kabid_tahfizh','kabid_kegiatan'];
  let moduleInstalled=false;
  function installModule(){
    if(typeof MODULE_GROUPS==='undefined')return false;
    let group=MODULE_GROUPS.find(x=>x.id==='laporan');
    if(!group){group={id:'laporan',label:'Laporan',roles:[],items:[]};MODULE_GROUPS.push(group)}
    group.roles=[...new Set([...(group.roles||[]),...PROMO_ROLES])];
    if(!group.items.some(x=>x.id==='laporan-promosi'))group.items.push({id:'laporan-promosi',label:'Laporan Promosi',roles:[...PROMO_ROLES],built:true,render});
    moduleInstalled=true;return true;
  }
  function hasActiveSession(){try{return Boolean(typeof getAuthToken==='function'&&getAuthToken())}catch(_){return false}}
  function inject(){if(moduleInstalled)return;const sb=document.getElementById('sidebar');if(!sb||!hasActiveSession()||sb.querySelector('[data-promotion-report]'))return;const b=document.createElement('div');b.className='nav-item';b.dataset.promotionReport='1';b.innerHTML='<span>📣 Laporan Promosi</span>';b.onclick=()=>{sb.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};sb.appendChild(b)}
  window.renderPromotionReport=render;window.deletePromotionReport=remove;
  installModule();
  const root=document.getElementById('sidebar')||document.body;new MutationObserver(()=>{clearTimeout(window.__prInject);window.__prInject=setTimeout(inject,60)}).observe(root,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,400));setTimeout(inject,1000);
})();
