/* CQlass — Badal Tahfizh
   Kabid Tahfizh mengatur badal halaqah. Pembadal dapat berasal dari guru/Kabid,
   daftar Pengabdian tanpa akun, atau nama manual. */
(function(){
  'use strict';
  if(window.__CQ_TAHFIZH_BADAL__) return;

  const BASE=(typeof SUPABASE_URL!=='undefined'?SUPABASE_URL:'https://lmglkxzemtvxcgktiord.supabase.co')+'/functions/v1/tahfizh-badal';
  const S={tab:'assign',boot:null,teacherFilter:'',editing:null,recap:null};
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const t5=v=>String(v||'').slice(0,5);
  function role(){try{return String(currentUser?.role||'').toLowerCase()}catch(_){return''}}
  function allowedRole(){return ['tahfizh','kabid_tahfizh','admin'].includes(role())}
  function token(){try{return typeof getAuthToken==='function'?getAuthToken():(localStorage.getItem('cqlass_session_token')||'')}catch(_){return''}}
  function headers(){const key=typeof SUPABASE_PUBLISHABLE_KEY!=='undefined'?SUPABASE_PUBLISHABLE_KEY:'';return{'Content-Type':'application/json','apikey':key,'Authorization':'Bearer '+key,'x-session-token':token()}}
  async function api(action,p={}){const r=await fetch(BASE,{method:'POST',headers:headers(),body:JSON.stringify({action,...p})});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||'Data belum dapat diproses.');return d}
  function emsg(m){return({forbidden:'Akses Badal Tahfizh hanya untuk Kabid Tahfizh.',invalid_input:'Lengkapi data badal terlebih dahulu.',halaqah_not_found:'Data halaqah tidak ditemukan pada tanggal tersebut.',substitute_required:'Pilih guru/Kabid pengganti.',same_teacher:'Guru asal dan guru badal tidak boleh sama.',substitute_not_allowed:'Guru/Kabid tersebut tidak tersedia sebagai pembadal.',external_not_found:'Data Pengabdian tidak ditemukan.',manual_name_required:'Isi nama pembadal manual.',teacher_conflict_schedule:'Guru pengganti masih memiliki jadwal mengajar pada jam tersebut.',teacher_conflict_academic_badal:'Guru pengganti sudah menjadi badal akademik pada jam tersebut.',teacher_conflict_tahfizh_badal:'Guru pengganti sudah menjadi badal Tahfizh pada jam tersebut.',teacher_conflict_halaqah:'Guru pengganti masih memiliki halaqah lain pada jam tersebut.'})[String(m||'')]||String(m||'Terjadi kendala.')}

  function css(){if(document.getElementById('cq-tahfizh-badal-css'))return;const s=document.createElement('style');s.id='cq-tahfizh-badal-css';s.textContent=`
    .tb{max-width:1500px;margin:auto;color:#153d38}.tb *{box-sizing:border-box}.tbhero{padding:20px 22px;border-radius:19px;background:linear-gradient(100deg,#fff,#eefaf6);border:1px solid #d9ebe6;margin-bottom:12px}.tbhero h2{margin:0;font:800 28px/1.1 Poppins,sans-serif}.tbhero h2 span{color:#2da17c}.tbhero p{margin:7px 0 0;font-size:10px;color:#657e78}.tbcard{background:#fff;border:1px solid #dcebe7;border-radius:15px;box-shadow:0 8px 22px rgba(18,61,57,.04);overflow:hidden}.tbtabs{display:flex;gap:7px;margin-bottom:10px}.tbtab{border:1px solid #cfe3de;background:#fff;border-radius:10px;padding:9px 13px;font-size:9px;font-weight:900;color:#246a61;cursor:pointer}.tbtab.on{background:#0d786d;color:#fff;border-color:#0d786d}.tbtools{display:flex;gap:9px;flex-wrap:wrap;align-items:end;padding:13px}.tbfield label{display:block;margin-bottom:5px;font-size:8px;font-weight:900;color:#6d817c;text-transform:uppercase}.tbfield input,.tbfield select,.tbfield textarea{min-width:220px;height:38px;border:1px solid #c5dcd6;border-radius:9px;background:#fff;padding:0 10px;font:500 10px Inter,sans-serif}.tbfield textarea{height:64px;padding:8px;resize:vertical}.tbbtn{border:0;border-radius:9px;padding:9px 12px;background:#0c7b70;color:#fff;font-size:9px;font-weight:900;cursor:pointer}.tbbtn.sec{background:#eef8f5;color:#0c7469;border:1px solid #cfe5df}.tbbtn.danger{background:#fff0f0;color:#a74249;border:1px solid #f2cdd0}.tbwrap{overflow:auto}.tbtable{width:100%;border-collapse:collapse;min-width:920px}.tbtable th,.tbtable td{padding:9px 10px;border-top:1px solid #edf2f0;font-size:9px;text-align:left;vertical-align:middle}.tbtable th{background:#f1f8f5;color:#657b75;font-size:8px;text-transform:uppercase}.tbpill{display:inline-block;padding:4px 7px;border-radius:999px;background:#e7f6f1;color:#0b756a;font-size:8px;font-weight:900}.tbpill.warn{background:#fff3d9;color:#986917}.tbpill.manual{background:#edf2ff;color:#5367a9}.tbpill.cancel{background:#f2f2f2;color:#777}.tbempty{padding:24px;text-align:center;color:#7b9089;font-size:9px}.tbeditor{margin:0 13px 13px;padding:13px;border:1px solid #d3e6e1;border-radius:13px;background:#f7fbfa}.tbeditor-title{font-size:10px;font-weight:900;margin-bottom:9px}.tbgrid{display:grid;grid-template-columns:1fr 1fr 1.2fr auto;gap:9px;align-items:end}.tbsource{margin-top:8px}.tbnote{margin-top:7px;font-size:8px;color:#738781;line-height:1.45}.tberr{margin-top:6px;font-size:8.5px;color:#a64b40;min-height:14px}.tbcheck{display:flex;gap:7px;align-items:center;font-size:9px;margin-top:7px}.tbrecapfilters{display:flex;gap:8px;align-items:end;flex-wrap:wrap;padding:13px}.tbsummary{padding:0 13px 11px;font-size:9px;color:#687f79}
    @media(max-width:900px){.tbgrid{grid-template-columns:1fr 1fr}.tbgrid .tbbtn{grid-column:1/-1}}@media(max-width:600px){.tbfield input,.tbfield select,.tbfield textarea{width:100%;min-width:0}.tbgrid{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  function subMap(){const m=new Map();for(const x of S.boot?.substitutions||[])m.set(`${x.original_teacher_id}|${x.class_id}|${t5(x.start_time)}`,x);return m}
  function teacherFilters(){const m=new Map();for(const x of S.boot?.sessions||[])if(!m.has(String(x.teacher_id)))m.set(String(x.teacher_id),x.teacher_name);return [...m.entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'id'))}
  function candidateOptions(originalId){const all=(S.boot?.candidates||[]).filter(x=>String(x.id)!==String(originalId));const gurus=all.filter(x=>x.kind!=='kabid');const kabids=all.filter(x=>x.kind==='kabid');const f=a=>a.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}${x.role_label&&x.role_label!=='Guru'?' · '+esc(x.role_label):''}</option>`).join('');return`${gurus.length?`<optgroup label="Guru">${f(gurus)}</optgroup>`:''}${kabids.length?`<optgroup label="Kabid">${f(kabids)}</optgroup>`:''}`}
  function externalOptions(){return(S.boot?.external||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.full_name)}</option>`).join('')}

  function editor(){const x=S.editing;if(!x)return'';return`<div class="tbeditor"><div class="tbeditor-title">${esc(x.teacher_name)} · ${esc(x.class_name)} · ${esc(t5(x.start_time))}–${esc(t5(x.end_time))}</div><div class="tbgrid"><div class="tbfield"><label>Sumber Pembadal</label><select id="tb-source"><option value="teacher">Guru / Kabid</option><option value="external">Pengabdian tersimpan</option><option value="manual">Ketik manual</option></select></div><div class="tbfield" id="tb-source-field"></div><div class="tbfield"><label>Alasan / Catatan</label><textarea id="tb-reason" placeholder="Contoh: sakit, izin, tugas lain"></textarea></div><button class="tbbtn" id="tb-save">Simpan Badal</button></div><div id="tb-manual-extra"></div><div class="tbnote">Pengabdian tidak perlu dibuatkan role/login. Role baru hanya diperlukan bila suatu hari mereka perlu masuk CQlass dan menginput data sendiri.</div><div id="tb-msg" class="tberr"></div></div>`}
  function renderSource(){const c=document.getElementById('content'),src=c?.querySelector('#tb-source')?.value||'teacher',host=c?.querySelector('#tb-source-field'),extra=c?.querySelector('#tb-manual-extra');if(!host||!extra||!S.editing)return;extra.innerHTML='';if(src==='teacher'){host.innerHTML=`<label>Guru / Kabid Badal</label><select id="tb-sub-teacher"><option value="">Pilih pembadal...</option>${candidateOptions(S.editing.teacher_id)}</select>`}else if(src==='external'){host.innerHTML=`<label>Pengabdian</label><select id="tb-sub-external"><option value="">Pilih Pengabdian...</option>${externalOptions()}</select>`;if(!(S.boot?.external||[]).length)extra.innerHTML='<div class="tbnote">Belum ada daftar Pengabdian tersimpan. Pilih “Ketik manual”, lalu centang simpan sebagai Pengabdian.</div>'}else{host.innerHTML='<label>Nama Pembadal</label><input id="tb-sub-manual" placeholder="Ketik nama Pengabdian / pembadal">';extra.innerHTML='<label class="tbcheck"><input type="checkbox" id="tb-save-pengabdian"> Simpan nama ini ke daftar Pengabdian agar muncul di dropdown berikutnya</label>'}}

  function assignRows(){const sm=subMap(),rows=(S.boot?.sessions||[]).filter(x=>!S.teacherFilter||String(x.teacher_id)===String(S.teacherFilter));if(!rows.length)return'<tr><td colspan="7" class="tbempty">Tidak ada jadwal Tahfizh pada filter ini.</td></tr>';return rows.map(x=>{const q=sm.get(`${x.teacher_id}|${x.class_id}|${t5(x.start_time)}`);return`<tr><td><b>${esc(t5(x.start_time))}–${esc(t5(x.end_time))}</b></td><td>${esc(x.class_name)}</td><td><b>${esc(x.teacher_name)}</b></td><td>${q?`<span class="tbpill">${esc(q.substitute_name)}</span>`:'<span class="tbpill warn">Belum dibadalkan</span>'}</td><td>${q?`<span class="tbpill ${q.substitute_type==='manual'?'manual':''}">${esc(q.substitute_type==='teacher'?'Guru/Kabid':q.substitute_type==='pengabdian'?'Pengabdian':'Manual')}</span>`:'—'}</td><td>${q?esc(q.reason||'—'):'—'}</td><td>${q?`<button class="tbbtn danger" data-tb-cancel="${esc(q.id)}">Batalkan</button>`:`<button class="tbbtn" data-tb-edit="${esc(x.key)}">Tentukan Badal</button>`}</td></tr>`}).join('')}

  function assignmentPage(){const filters=teacherFilters();return`<div class="tb"><div class="tbhero"><h2>Badal <span>Tahfizh</span></h2><p>Kelola guru pengganti halaqah Tahfizh berdasarkan jadwal kelas. Pembadal bisa dari guru/Kabid, Pengabdian tanpa akun, atau nama manual.</p></div><div class="tbtabs"><button class="tbtab on" data-tb-tab="assign">Penugasan Badal</button><button class="tbtab" data-tb-tab="recap">Rekap Badal</button></div><div class="tbcard"><div class="tbtools"><div class="tbfield"><label>Tanggal</label><input type="date" id="tb-date" value="${esc(S.boot?.date||'')}"></div><div class="tbfield"><label>Filter Guru Tahfizh</label><select id="tb-teacher-filter"><option value="">Semua guru / semua halaqah</option>${filters.map(([id,n])=>`<option value="${esc(id)}" ${String(id)===String(S.teacherFilter)?'selected':''}>${esc(n)}</option>`).join('')}</select></div><button class="tbbtn sec" id="tb-load">Muat Jadwal</button></div>${editor()}<div class="tbwrap"><table class="tbtable"><thead><tr><th>Jam</th><th>Kelas / Halaqah</th><th>Guru Tahfizh</th><th>Guru Badal</th><th>Jenis</th><th>Catatan</th><th>Aksi</th></tr></thead><tbody>${assignRows()}</tbody></table></div></div></div>`}

  function recapRows(){const rows=S.recap?.items||[];if(!rows.length)return'<tr><td colspan="9" class="tbempty">Belum ada riwayat badal pada periode ini.</td></tr>';return rows.map(x=>`<tr><td>${esc(x.work_date)}</td><td>${esc(t5(x.start_time))}–${esc(t5(x.end_time))}</td><td>${esc(x.class_name||'—')}</td><td>${esc(x.original_teacher_name||'—')}</td><td><b>${esc(x.substitute_name||'—')}</b></td><td><span class="tbpill ${x.substitute_type==='manual'?'manual':''}">${esc(x.substitute_type==='teacher'?'Guru/Kabid':x.substitute_type==='pengabdian'?'Pengabdian':'Manual')}</span></td><td>${esc(x.reason||'—')}</td><td><span class="tbpill ${x.status==='cancelled'?'cancel':''}">${x.status==='active'?'Aktif':'Dibatalkan'}</span></td><td>${x.status==='active'?`<button class="tbbtn danger" data-tb-recap-cancel="${esc(x.id)}">Batalkan</button>`:'—'}</td></tr>`).join('')}
  function recapPage(){const today=S.boot?.date||new Date().toISOString().slice(0,10),from=S.recap?.from||today,to=S.recap?.to||today;return`<div class="tb"><div class="tbhero"><h2>Rekap <span>Badal Tahfizh</span></h2><p>Riwayat guru badal Tahfizh, termasuk pembadal dari Pengabdian atau input manual.</p></div><div class="tbtabs"><button class="tbtab" data-tb-tab="assign">Penugasan Badal</button><button class="tbtab on" data-tb-tab="recap">Rekap Badal</button></div><div class="tbcard"><div class="tbrecapfilters"><div class="tbfield"><label>Dari</label><input id="tb-from" type="date" value="${esc(from)}"></div><div class="tbfield"><label>Sampai</label><input id="tb-to" type="date" value="${esc(to)}"></div><button class="tbbtn sec" id="tb-recap-load">Muat Rekap</button></div><div class="tbsummary">Total ${Number(S.recap?.items?.length||0)} penugasan pada periode terpilih.</div><div class="tbwrap"><table class="tbtable"><thead><tr><th>Tanggal</th><th>Jam</th><th>Kelas</th><th>Guru Asal</th><th>Pembadal</th><th>Jenis</th><th>Catatan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${recapRows()}</tbody></table></div></div></div>`}

  function draw(){const c=document.getElementById('content');if(!c)return;c.innerHTML=S.tab==='recap'?recapPage():assignmentPage();wire()}
  async function load(date,keep=true){const c=document.getElementById('content');if(c)c.innerHTML='<div class="tb"><div class="tbcard tbempty">Memuat Badal Tahfizh...</div></div>';const prev=keep?S.teacherFilter:'';S.boot=await api('bootstrap',{work_date:date});const ids=new Set(teacherFilters().map(x=>String(x[0])));S.teacherFilter=prev&&ids.has(String(prev))?prev:'';S.editing=null;draw()}
  async function loadRecap(from,to){S.recap=await api('recap',{from,to});draw()}

  function wire(){const c=document.getElementById('content');if(!c)return;c.querySelectorAll('[data-tb-tab]').forEach(b=>b.addEventListener('click',async()=>{S.tab=b.dataset.tbTab;if(S.tab==='recap'&&!S.recap){const d=S.boot?.date||'';S.recap=await api('recap',{from:d,to:d})}draw()}));if(S.tab==='assign'){c.querySelector('#tb-load')?.addEventListener('click',()=>load(c.querySelector('#tb-date')?.value||'',true).catch(e=>{c.innerHTML=`<div class="tb"><div class="tbcard tbempty">${esc(emsg(e.message))}</div></div>`}));c.querySelector('#tb-teacher-filter')?.addEventListener('change',e=>{S.teacherFilter=e.target.value;S.editing=null;draw()});c.querySelectorAll('[data-tb-edit]').forEach(b=>b.addEventListener('click',()=>{S.editing=(S.boot?.sessions||[]).find(x=>String(x.key)===String(b.dataset.tbEdit))||null;draw()}));c.querySelectorAll('[data-tb-cancel]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Batalkan badal Tahfizh ini?'))return;try{await api('cancel',{id:b.dataset.tbCancel});await load(S.boot.date,true);if(typeof showToast==='function')showToast('Badal Tahfizh dibatalkan.')}catch(e){if(typeof showToast==='function')showToast(emsg(e.message),true)}}));if(S.editing){renderSource();c.querySelector('#tb-source')?.addEventListener('change',renderSource);c.querySelector('#tb-save')?.addEventListener('click',async()=>{const src=c.querySelector('#tb-source')?.value||'teacher',payload={work_date:S.boot.date,class_id:S.editing.class_id,original_teacher_id:S.editing.teacher_id,start_time:t5(S.editing.start_time),end_time:t5(S.editing.end_time),substitute_source:src,reason:c.querySelector('#tb-reason')?.value||''};if(src==='teacher')payload.substitute_teacher_id=c.querySelector('#tb-sub-teacher')?.value||'';else if(src==='external')payload.substitute_external_person_id=c.querySelector('#tb-sub-external')?.value||'';else{payload.substitute_name_manual=c.querySelector('#tb-sub-manual')?.value||'';payload.save_as_pengabdian=!!c.querySelector('#tb-save-pengabdian')?.checked}const m=c.querySelector('#tb-msg');try{await api('assign',payload);await load(S.boot.date,true);if(typeof showToast==='function')showToast('Badal Tahfizh berhasil disimpan.')}catch(e){if(m)m.textContent=emsg(e.message)}})}}else{c.querySelector('#tb-recap-load')?.addEventListener('click',()=>loadRecap(c.querySelector('#tb-from')?.value||'',c.querySelector('#tb-to')?.value||'').catch(e=>{if(typeof showToast==='function')showToast(emsg(e.message),true)}));c.querySelectorAll('[data-tb-recap-cancel]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Batalkan badal Tahfizh ini?'))return;try{await api('cancel',{id:b.dataset.tbRecapCancel});await loadRecap(S.recap.from,S.recap.to)}catch(e){if(typeof showToast==='function')showToast(emsg(e.message),true)}}))}}

  async function render(content){css();if(!allowedRole()){content.innerHTML='<div class="card">Akses Badal Tahfizh tidak tersedia untuk akun ini.</div>';return}try{await load('',false)}catch(e){content.innerHTML=`<div class="tb"><div class="tbcard tbempty">${esc(emsg(e.message))}</div></div>`}}
  function ensureMenu(){try{if(typeof MODULE_GROUPS==='undefined'||!Array.isArray(MODULE_GROUPS))return false;let g=MODULE_GROUPS.find(x=>x&&Array.isArray(x.roles)&&x.roles.some(r=>['tahfizh','kabid_tahfizh'].includes(r))&&String(x.id||'')!=='laporan');if(!g){g={id:'tahfizh-ops',label:'TAHFIZH',roles:['tahfizh','kabid_tahfizh'],items:[]};MODULE_GROUPS.push(g)}else{g.roles=[...new Set([...(g.roles||[]),'tahfizh','kabid_tahfizh'])]}if(!Array.isArray(g.items))g.items=[];let it=g.items.find(x=>x&&x.id==='tahfizh-badal');if(!it){it={id:'tahfizh-badal',label:'Badal Tahfizh',roles:['tahfizh','kabid_tahfizh'],built:true,render};g.items.push(it)}else{it.label='Badal Tahfizh';it.roles=['tahfizh','kabid_tahfizh'];it.built=true;it.render=render}return true}catch(e){console.warn('Badal Tahfizh menu',e);return false}}
  function install(){css();ensureMenu();if(typeof renderSidebar==='function'&&!renderSidebar.__cqTahBadal){const old=renderSidebar;renderSidebar=function(){ensureMenu();return old.apply(this,arguments)};renderSidebar.__cqTahBadal=true}if(['tahfizh','kabid_tahfizh'].includes(role())&&typeof renderSidebar==='function')renderSidebar();window.renderTahfizhBadal=render;window.__CQ_TAHFIZH_BADAL__=true}
  let n=0;(function wait(){if(typeof MODULE_GROUPS!=='undefined'&&typeof renderSidebar==='function'){install();return}if(++n<80)setTimeout(wait,150)})();
})();