import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-session-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8"};
const URL=Deno.env.get("SUPABASE_URL")!;
const T=(v:any)=>String(v??"").trim();
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"Cache-Control":"no-store"}});
const TARGET_TP=2;
function secret(){const p=Deno.env.get("SUPABASE_SECRET_KEYS");if(p){try{const x=JSON.parse(p);if(x?.default)return String(x.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||""}
const sb=createClient(URL,secret(),{auth:{persistSession:false,autoRefreshToken:false}});
const uniq=(a:any[])=>[...new Set(a.filter(Boolean))];
const latest=(rows:any[])=>rows.map(x=>T(x.updated_at||x.created_at)).filter(Boolean).sort().pop()||null;
async function paged(factory:()=>any){const out:any[]=[];for(let from=0;;from+=1000){const{data,error}=await factory().range(from,from+999);if(error)throw error;out.push(...(data||[]));if(!data||data.length<1000)break}return out}
async function proxy(req:Request,body:any){const r=await fetch(`${URL}/functions/v1/hrd-live-report-v2`,{method:"POST",headers:{"Content-Type":"application/json","apikey":req.headers.get("apikey")||"","Authorization":req.headers.get("Authorization")||"","x-session-token":req.headers.get("x-session-token")||""},body:JSON.stringify(body)});const d=await r.json().catch(()=>({success:false,error:"invalid_upstream"}));return{r,d}}
function recalc(t:any){const req=(t.categories||[]).filter((c:any)=>c?.applicable),complete=req.filter((c:any)=>c.status==="present").length,partial=req.filter((c:any)=>c.status==="partial").length,missing=req.filter((c:any)=>c.status==="missing").length;t.required_count=req.length;t.completed_count=complete;t.partial_count=partial;t.missing_count=missing;t.missing_categories=req.filter((c:any)=>c.status==="missing").map((c:any)=>c.label);t.partial_categories=req.filter((c:any)=>c.status==="partial").map((c:any)=>c.label);t.issue_units=missing+partial;t.completeness_index=req.length?Math.round(((complete+partial*.5)/req.length)*100):null}
async function enrich(data:any,start:string,end:string){
  const teachers=data.teachers||[],teacherIds=uniq(teachers.map((t:any)=>T(t.teacher_id)));if(!teacherIds.length)return;
  const{data:unit}=await sb.from("school_units").select("id").eq("code","SD").maybeSingle();if(!unit)return;
  const{data:year}=await sb.from("academic_years").select("id,name").eq("school_unit_id",unit.id).eq("is_active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!year)return;
  const{data:sem}=await sb.from("semesters").select("semester_no").eq("academic_year_id",year.id).eq("is_active",true).maybeSingle();const semesterNo=Number(sem?.semester_no||1);
  const [asgR,classR,subR,enrR,objR,activities]=await Promise.all([
    sb.from("teacher_subject_assignments").select("teacher_id,class_id,subject_id").eq("academic_year_id",year.id).eq("semester_no",semesterNo).eq("is_active",true).in("teacher_id",teacherIds),
    sb.from("classes").select("id,name,grade_level").eq("academic_year_id",year.id).eq("is_active",true),
    sb.from("subjects").select("id,name,code"),
    sb.from("student_enrollments").select("student_id,class_id").eq("academic_year_id",year.id).eq("semester_no",semesterNo).eq("is_active",true),
    sb.from("learning_objectives").select("id,subject_id,grade_level,code,description,topic,sort_order").eq("academic_year_id",year.id).eq("semester_no",semesterNo).eq("is_active",true),
    sb.from("teacher_timesheet_activities").select("id,teacher_id,work_date,start_time,end_time,activity,note,created_at,updated_at,source").in("teacher_id",teacherIds).gte("work_date",start).lte("work_date",end).order("work_date").order("start_time")
  ]);for(const q of[asgR,classR,subR,enrR,objR,activities])if((q as any).error)throw (q as any).error;
  const scores=await paged(()=>sb.from("academic_scores").select("teacher_id,class_id,subject_id,student_id,learning_objective_id,assessment_type,score,created_at,updated_at").eq("academic_year_id",year.id).eq("semester_no",semesterNo).is("deleted_at",null).not("score","is",null).in("teacher_id",teacherIds).in("assessment_type",["TP","TUGAS_1","TUGAS_2"]));
  const cm=new Map((classR.data||[]).map((x:any)=>[T(x.id),x])),sm=new Map((subR.data||[]).map((x:any)=>[T(x.id),x]));
  const roster=new Map<string,Set<string>>();for(const e of enrR.data||[]){const cid=T(e.class_id);if(!roster.has(cid))roster.set(cid,new Set());roster.get(cid)!.add(T(e.student_id))}
  const om=new Map<string,any>((objR.data||[]).map((x:any)=>[T(x.id),x]));
  const scoreByTeacher=new Map<string,any[]>();for(const s of scores){const id=T(s.teacher_id);if(!scoreByTeacher.has(id))scoreByTeacher.set(id,[]);scoreByTeacher.get(id)!.push(s)}
  const actByTeacher=new Map<string,any[]>();for(const a of activities.data||[]){const id=T(a.teacher_id);if(!actByTeacher.has(id))actByTeacher.set(id,[]);actByTeacher.get(id)!.push(a)}
  for(const t of teachers){
    const tid=T(t.teacher_id),assignments=(asgR.data||[]).filter((a:any)=>T(a.teacher_id)===tid),ts=scoreByTeacher.get(tid)||[],detail:any[]=[];
    const seen=new Set<string>();
    for(const a of assignments){const cid=T(a.class_id),sid=T(a.subject_id),key=`${cid}|${sid}`;if(seen.has(key))continue;seen.add(key);const cl:any=cm.get(cid)||{},sub:any=sm.get(sid)||{},rs=roster.get(cid)||new Set<string>(),rows=ts.filter((x:any)=>T(x.class_id)===cid&&T(x.subject_id)===sid);
      const tpRows=rows.filter((x:any)=>T(x.assessment_type)==="TP"&&T(x.learning_objective_id));const byObj=new Map<string,any[]>();for(const x of tpRows){const oid=T(x.learning_objective_id);if(!byObj.has(oid))byObj.set(oid,[]);byObj.get(oid)!.push(x)}
      const actualTp=[...byObj.entries()].map(([oid,r])=>{const o:any=om.get(oid)||{},students=uniq(r.map((x:any)=>T(x.student_id))).length,vals=r.map((x:any)=>Number(x.score)).filter((n:number)=>Number.isFinite(n)),avg=vals.length?Math.round(vals.reduce((z:number,v:number)=>z+v,0)/vals.length*10)/10:null;return{id:oid,source_code:T(o.code)||null,description:T(o.description)||T(o.topic)||"Tujuan pembelajaran",scored_students:students,average_score:avg,last_updated_at:latest(r),complete:rs.size?students>=rs.size:students>0}}).sort((x,y)=>T(x.source_code).localeCompare(T(y.source_code),"id",{numeric:true}));
      const fullTp=actualTp.filter(x=>x.complete);const taskTypes=["TUGAS_1","TUGAS_2"].filter(type=>{const rr=rows.filter((x:any)=>T(x.assessment_type)===type),n=uniq(rr.map((x:any)=>T(x.student_id))).length;return rs.size?n>=rs.size:n>0});
      const effective=Math.max(fullTp.length,fullTp.length===0?taskTypes.length:fullTp.length===1&&taskTypes.includes("TUGAS_2")?2:fullTp.length);
      const visible=actualTp.map((x,i)=>({id:x.id,code:`TP${i+1}`,source_code:x.source_code,description:x.description,scored_students:x.scored_students,average_score:x.average_score,last_updated_at:x.last_updated_at,status:x.scored_students>0?"entered":"missing",complete:x.complete}));
      detail.push({class_id:cid,class_name:T(cl.name)||"Kelas",grade_level:Number(cl.grade_level)||0,subject_id:sid,subject_name:T(sub.name)||T(sub.code)||"Mapel",tp:visible,entered_tp:Math.min(effective,TARGET_TP),actual_tp_count:actualTp.length,complete_tp_count:fullTp.length,legacy_weekly_evidence:taskTypes,report_minimum_tp:TARGET_TP,report_complete:effective>=TARGET_TP,students_scored:uniq(rows.map((x:any)=>T(x.student_id))).length,score_rows:rows.length,last_updated_at:latest(rows),remaining_to_target:Math.max(0,TARGET_TP-effective)});
    }
    detail.sort((a,b)=>a.class_name.localeCompare(b.class_name,"id")||a.subject_name.localeCompare(b.subject_name,"id"));
    const done=detail.filter(x=>x.report_complete).length,sum=detail.reduce((z,x)=>z+Number(x.entered_tp||0),0),studentCount=uniq(ts.map((x:any)=>T(x.student_id))).length;
    t.academic_tp_detail=detail;t.academic_tp_summary={assignments:detail.length,assignments_complete:done,minimum_tp_per_assignment:TARGET_TP,target_tp_total:detail.length*TARGET_TP,entered_tp:sum,students_scored:studentCount,score_rows:ts.length};
    const ac=(t.categories||[]).find((c:any)=>c.key==="academic");if(ac){ac.label="Nilai TP / Rapor";ac.applicable=detail.length>0;ac.completed_assignments=done;ac.expected_assignments=detail.length;ac.minimum_tp_per_assignment=TARGET_TP;ac.item_count=sum;ac.status=!detail.length?"na":done===detail.length?"present":sum>0?"partial":"missing";ac.note=`Target pekan ini: minimal ${TARGET_TP} TP bernilai pada setiap kelas-mapel. TP master lain di luar target pekan ini tidak mengurangi kelengkapan.`;ac.items=detail.map(x=>({id:`${x.class_id}|${x.subject_id}`,title:`${x.subject_name} — ${x.class_name}`,description:x.report_complete?`Target ${TARGET_TP} TP pekan ini terpenuhi`:`${x.entered_tp}/${TARGET_TP} TP target pekan ini`,created_at:x.last_updated_at,status:x.report_complete?"present":x.entered_tp?"partial":"missing"}));ac.last_created_at=latest(ac.items)}
    const manual=actByTeacher.get(tid)||[],tc=(t.categories||[]).find((c:any)=>c.key==="timesheet");if(tc){tc.label="Timesheet";tc.applicable=true;tc.items=[];tc.activity_items=manual.map((x:any)=>({id:x.id,title:T(x.activity)||"Aktivitas Timesheet",description:[T(x.start_time).slice(0,5)&&T(x.end_time).slice(0,5)?`${T(x.start_time).slice(0,5)}–${T(x.end_time).slice(0,5)}`:"",T(x.note)].filter(Boolean).join(" · "),period_start:x.work_date,created_at:x.updated_at||x.created_at}));tc.activity_item_count=tc.activity_items.length;tc.item_count=tc.activity_items.length;tc.status=tc.item_count>0?"present":"missing";tc.note="Timesheet hanya berisi aktivitas kerja yang dicatat pada Timesheet. Jam mengajar, badal, UKS terjadwal, briefing, penyambutan, MT, literasi, istirahat/snack, ishoma, dan rutinitas lain tidak dihitung sebagai isian Timesheet.";tc.last_created_at=latest(manual)}
    t.categories=(t.categories||[]).filter((c:any)=>c.key!=="work_activity");recalc(t);
  }
  data.detail_version=6;data.summary={...(data.summary||{}),academic_minimum_tp_per_assignment:TARGET_TP,timesheet_definition:"timesheet_activity"};
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return J({success:false,error:"method_not_allowed"},405);try{const body=await req.json().catch(()=>({})),{r,d}=await proxy(req,body);if(!r.ok||d?.success===false)return J(d,r.status);if(T(body.action).toLowerCase()==="administration")await enrich(d,T(body.start),T(body.end));return J(d,r.status)}catch(e){console.error("hrd-live-report-v3",e);return J({success:false,error:"server_error",message:T((e as any)?.message)||"internal_error"},500)}});