import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";

const url=Deno.env.get("SUPABASE_URL")!;
const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")!;
const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, apikey, authorization, x-session-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const reply=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
const txt=(v:any)=>String(v??"").trim(); const low=(v:any)=>txt(v).toLowerCase();
const grade=(v:any)=>{const g=txt(v).toUpperCase();return ["A","B","C","D"].includes(g)?g:""};
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=txt(req.headers.get("x-session-token"));if(!raw)return null;const {data:s}=await sb.from("user_sessions").select("user_account_id,expires_at,revoked_at").eq("token_hash",await hash(raw)).maybeSingle();if(!s||s.revoked_at||!s.expires_at||new Date(s.expires_at).getTime()<=Date.now())return null;const {data:a}=await sb.from("user_accounts").select("id,teacher_id,username,status").eq("id",s.user_account_id).maybeSingle();if(!a)return null;const roles:string[]=[];const {data:ar}=await sb.from("user_account_roles").select("role_code,role,is_active").eq("user_account_id",a.id).eq("is_active",true);for(const r of ar||[])roles.push(low(r.role_code||r.role));if(a.teacher_id){const {data:tr}=await sb.from("user_roles").select("role_code,is_active").eq("teacher_id",a.teacher_id).eq("is_active",true);for(const r of tr||[])roles.push(low(r.role_code));}if(low(a.username)==="admin")roles.push("admin");return {...a,roles:[...new Set(roles)]}}
const canView=(a:any)=>a?.roles?.some((r:string)=>["kabid_kegiatan","kegiatan","pimpinan","admin"].includes(r));
const canEdit=(a:any)=>a?.roles?.some((r:string)=>["kabid_kegiatan","kegiatan"].includes(r));
async function period(){const {data:y}=await sb.from("academic_years").select("id,name").eq("is_active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!y)throw Error("academic_year_missing");const {data:s}=await sb.from("semesters").select("semester_no").eq("academic_year_id",y.id).eq("is_active",true).limit(1).maybeSingle();return{academic_year_id:y.id,academic_year:y.name,semester_no:Number(s?.semester_no||1)}}
async function listRows(p:any){
  const {data:ext,error:ee}=await sb.from("extracurricular_external_students").select("id,student_id,activity_name,institution_name,is_active,updated_at").eq("academic_year_id",p.academic_year_id).eq("semester_no",p.semester_no).eq("is_active",true).order("activity_name");
  if(ee)throw ee;
  const all=ext||[];const allSids=[...new Set(all.map((x:any)=>x.student_id).filter(Boolean))] as string[];if(!all.length)return [];
  const {data:internal,error:ie}=await sb.from("extracurricular_members").select("student_id,status").eq("academic_year_id",p.academic_year_id).in("student_id",allSids);if(ie)throw ie;
  const internalIds=new Set((internal||[]).filter((x:any)=>["aktif","active"].includes(low(x.status))).map((x:any)=>x.student_id));
  const xs=all.filter((x:any)=>!internalIds.has(x.student_id));const extIds=xs.map((x:any)=>x.id);const sids=[...new Set(xs.map((x:any)=>x.student_id).filter(Boolean))] as string[];if(!xs.length)return [];
  const [{data:ass,error:ae},{data:students,error:se},{data:enr,error:ene}]=await Promise.all([
    sb.from("extracurricular_external_assessments").select("id,external_student_id,student_id,activity_grade,skill_grade,competition_grade,competition_note,updated_at").eq("academic_year_id",p.academic_year_id).eq("semester_no",p.semester_no).eq("assessment_period","PTS").in("external_student_id",extIds),
    sb.from("students").select("id,full_name,nis,nisn,status").in("id",sids),
    sb.from("student_enrollments").select("student_id,class_id").eq("academic_year_id",p.academic_year_id).eq("semester_no",p.semester_no).eq("is_active",true).in("student_id",sids)
  ]);
  if(ae)throw ae;if(se)throw se;if(ene)throw ene;
  const cids=[...new Set((enr||[]).map((x:any)=>x.class_id).filter(Boolean))] as string[];const {data:classes,error:ce}=cids.length?await sb.from("classes").select("id,name,code").in("id",cids):{data:[],error:null};if(ce)throw ce;
  const sm=new Map((students||[]).map((x:any)=>[x.id,x]));const cm=new Map((classes||[]).map((x:any)=>[x.id,x]));const em=new Map((enr||[]).map((x:any)=>[x.student_id,x.class_id]));const am=new Map((ass||[]).map((x:any)=>[x.external_student_id,x]));
  return xs.map((x:any)=>{const s=sm.get(x.student_id)||{},a=am.get(x.id)||{},c=cm.get(em.get(x.student_id))||{};return{external_student_id:x.id,assessment_id:a.id||null,has_grade_data:Boolean(a.id),student_id:x.student_id,student_name:s.full_name||"-",nis:s.nis||s.nisn||"",class_name:c.name||c.code||"-",activity_name:x.activity_name||"Ekskul Eksternal",institution_name:x.institution_name||"",activity_grade:a.activity_grade||"",skill_grade:a.skill_grade||"",competition_grade:a.competition_grade||"",competition_note:a.competition_note||"",updated_at:a.updated_at||x.updated_at||null}}).sort((a:any,b:any)=>a.class_name.localeCompare(b.class_name,"id",{numeric:true})||a.student_name.localeCompare(b.student_name,"id"));
}
async function saveAssessment(p:any,b:any){const extId=txt(b.external_student_id);if(!extId)return reply({success:false,error:"external_student_required"},400);const ag=grade(b.activity_grade),sg=grade(b.skill_grade),cg=grade(b.competition_grade),note=txt(b.competition_note);if(!ag||!sg||!cg)return reply({success:false,error:"grades_must_be_a_to_d"},400);if(note.length>500)return reply({success:false,error:"competition_note_too_long"},400);const {data:ext}=await sb.from("extracurricular_external_students").select("id,student_id,is_active").eq("id",extId).eq("academic_year_id",p.academic_year_id).eq("semester_no",p.semester_no).eq("is_active",true).maybeSingle();if(!ext)return reply({success:false,error:"external_student_not_found"},404);const {data:im}=await sb.from("extracurricular_members").select("id,status").eq("student_id",ext.student_id).eq("academic_year_id",p.academic_year_id);if((im||[]).some((x:any)=>["aktif","active"].includes(low(x.status))))return reply({success:false,error:"student_is_internal_extracurricular"},409);const now=new Date().toISOString();const {error}=await sb.from("extracurricular_external_assessments").upsert({external_student_id:ext.id,student_id:ext.student_id,academic_year_id:p.academic_year_id,semester_no:p.semester_no,assessment_period:"PTS",activity_grade:ag,skill_grade:sg,competition_grade:cg,competition_note:note||null,source_system:"CQLASS_KABID",updated_at:now},{onConflict:"external_student_id,assessment_period"});if(error)throw error;return reply({success:true,rows:await listRows(p)})}
async function deleteAssessment(p:any,b:any){const extId=txt(b.external_student_id);if(!extId)return reply({success:false,error:"external_student_required"},400);const {error}=await sb.from("extracurricular_external_assessments").delete().eq("external_student_id",extId).eq("academic_year_id",p.academic_year_id).eq("semester_no",p.semester_no).eq("assessment_period","PTS");if(error)throw error;return reply({success:true,rows:await listRows(p)})}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{const a=await auth(req);if(!a)return reply({success:false,error:"session_invalid"},401);if(!canView(a))return reply({success:false,error:"forbidden"},403);const b=await req.json().catch(()=>({}));const action=low(b.action),p=await period();if(action==="list")return reply({success:true,academic_year:p.academic_year,semester_no:p.semester_no,can_edit:canEdit(a),rows:await listRows(p)});if(!canEdit(a))return reply({success:false,error:"readonly"},403);if(action==="save")return await saveAssessment(p,b);if(action==="delete")return await deleteAssessment(p,b);return reply({success:false,error:"unknown_action"},400)}catch(e){console.error(e);return reply({success:false,error:txt((e as any)?.message)||"internal_error"},500)}});
