import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-session-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...H,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}),T=(v:any)=>String(v??"").trim(),L=(v:any)=>T(v).toLowerCase();
function key(){const p=Deno.env.get("SUPABASE_SECRET_KEYS");if(p){try{const x=JSON.parse(p);if(x?.default)return String(x.default)}catch{}}const k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY");if(!k)throw Error("service_key_missing");return k}
const sb=createClient(Deno.env.get("SUPABASE_URL")!,key(),{auth:{persistSession:false,autoRefreshToken:false}});
async function hash(s:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const tok=T(req.headers.get("x-session-token"));if(!tok)return null;const{data:ss}=await sb.from("user_sessions").select("user_account_id,expires_at,revoked_at").eq("token_hash",await hash(tok)).maybeSingle();if(!ss||ss.revoked_at||!ss.expires_at||Date.parse(ss.expires_at)<=Date.now())return null;const{data:a}=await sb.from("user_accounts").select("id,username,status").eq("id",ss.user_account_id).maybeSingle();if(!a||["nonaktif","inactive","disabled","blocked"].includes(L(a.status)))return null;if(L(a.username)==="admin")return a;const{data:r}=await sb.from("user_account_roles").select("role_code,role").eq("user_account_id",a.id).eq("is_active",true);return(r||[]).some((x:any)=>L(x.role_code||x.role)==="admin")?a:null}
async function unit(){const{data,error}=await sb.from("school_units").select("id,name").limit(1).maybeSingle();if(error)throw error;if(!data)throw Error("school_unit_missing");return data}
async function list(){const u=await unit();const{data:y,error}=await sb.from("academic_years").select("id,name,start_date,end_date,is_active,created_at").eq("school_unit_id",u.id).order("created_at",{ascending:false});if(error)throw error;const ids=(y||[]).map((x:any)=>x.id);let sem:any[]=[];if(ids.length){const q=await sb.from("semesters").select("id,academic_year_id,semester_no,start_date,end_date,is_active").in("academic_year_id",ids).order("semester_no");if(q.error)throw q.error;sem=q.data||[]}return{school_unit:u,years:(y||[]).map((x:any)=>({...x,semesters:sem.filter((s:any)=>s.academic_year_id===x.id)}))}}
function validName(v:string){const m=v.match(/^(\d{4})\/(\d{4})$/);return!!m&&Number(m[2])===Number(m[1])+1}
async function createYear(b:any){const u=await unit(),name=T(b.name);if(!validName(name))return J({success:false,error:"academic_year_invalid"},400);const{data:ex}=await sb.from("academic_years").select("id").eq("school_unit_id",u.id).eq("name",name).maybeSingle();if(ex)return J({success:false,error:"academic_year_exists"},409);const{data:y,error}=await sb.from("academic_years").insert({school_unit_id:u.id,name,start_date:T(b.start_date)||null,end_date:T(b.end_date)||null,is_active:false}).select("id").single();if(error)throw error;const{error:se}=await sb.from("semesters").insert([{academic_year_id:y.id,semester_no:1,is_active:false},{academic_year_id:y.id,semester_no:2,is_active:false}]);if(se)throw se;return J({success:true,...await list()})}
async function activate(b:any){const yearId=T(b.academic_year_id),no=Number(b.semester_no);if(!yearId||![1,2].includes(no))return J({success:false,error:"period_invalid"},400);const u=await unit();const{data:y}=await sb.from("academic_years").select("id").eq("id",yearId).eq("school_unit_id",u.id).maybeSingle();if(!y)return J({success:false,error:"academic_year_not_found"},404);const{data:s}=await sb.from("semesters").select("id").eq("academic_year_id",yearId).eq("semester_no",no).maybeSingle();if(!s)return J({success:false,error:"semester_not_found"},404);const{data:ys}=await sb.from("academic_years").select("id").eq("school_unit_id",u.id);const ids=(ys||[]).map((x:any)=>x.id),now=new Date().toISOString();let q=await sb.from("academic_years").update({is_active:false,updated_at:now}).eq("school_unit_id",u.id);if(q.error)throw q.error;if(ids.length){q=await sb.from("semesters").update({is_active:false,updated_at:now}).in("academic_year_id",ids);if(q.error)throw q.error}q=await sb.from("academic_years").update({is_active:true,updated_at:now}).eq("id",yearId);if(q.error)throw q.error;q=await sb.from("semesters").update({is_active:true,updated_at:now}).eq("id",s.id);if(q.error)throw q.error;return J({success:true,...await list()})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({success:false,error:"method_not_allowed"},405);try{if(!await auth(req))return J({success:false,error:"forbidden"},403);const b=await req.json().catch(()=>({})),a=L(b.action||"list");if(a==="list")return J({success:true,...await list()});
if(a==="effective_days"){const yearId=T(b.academic_year_id),no=Number(b.semester_no),period=T(b.assessment_period).toUpperCase();if(!yearId||![1,2].includes(no)||!["PTS","PAS"].includes(period))return J({success:false,error:"period_invalid"},400);const u=await unit();const{data:y}=await sb.from("academic_years").select("id").eq("id",yearId).eq("school_unit_id",u.id).maybeSingle();if(!y)return J({success:false,error:"academic_year_not_found"},404);const{data:classes,error:ce}=await sb.from("classes").select("id,name,code,grade_level,rombel,is_active").eq("school_unit_id",u.id).eq("academic_year_id",yearId).eq("is_active",true).order("grade_level").order("name");if(ce)throw ce;const{data:days,error:de}=await sb.from("class_effective_days").select("class_id,effective_days").eq("academic_year_id",yearId).eq("semester_no",no).eq("assessment_period",period);if(de)throw de;const dm=new Map((days||[]).map((x:any)=>[x.class_id,x.effective_days]));return J({success:true,classes:(classes||[]).map((x:any)=>({...x,effective_days:dm.get(x.id)??null}))})}
if(a==="save_effective_days"){const yearId=T(b.academic_year_id),no=Number(b.semester_no),period=T(b.assessment_period).toUpperCase(),rows=Array.isArray(b.rows)?b.rows:[];if(!yearId||![1,2].includes(no)||!["PTS","PAS"].includes(period))return J({success:false,error:"period_invalid"},400);const u=await unit();const{data:y}=await sb.from("academic_years").select("id").eq("id",yearId).eq("school_unit_id",u.id).maybeSingle();if(!y)return J({success:false,error:"academic_year_not_found"},404);for(const r of rows){const n=Number(r.effective_days);if(!r.class_id||!Number.isInteger(n)||n<0||n>366)return J({success:false,error:"effective_days_invalid"},400);const{data:cl}=await sb.from("classes").select("id").eq("id",T(r.class_id)).eq("academic_year_id",yearId).eq("school_unit_id",u.id).maybeSingle();if(!cl)return J({success:false,error:"class_not_in_year"},400)}if(rows.length){const payload=rows.map((r:any)=>({school_unit_id:u.id,academic_year_id:yearId,semester_no:no,assessment_period:period,class_id:T(r.class_id),effective_days:Number(r.effective_days),updated_at:new Date().toISOString()}));const{error}=await sb.from("class_effective_days").upsert(payload,{onConflict:"academic_year_id,semester_no,assessment_period,class_id"});if(error)throw error}return J({success:true})}
if(a==="create_year")return await createYear(b);if(a==="activate_period")return await activate(b);return J({success:false,error:"unknown_action"},400)}catch(e){console.error("admin-academic-period",e);return J({success:false,error:T((e as any)?.message)||"internal_error"},500)}});
