const state={classes:[],period:null,api:null,viewerKey:''};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

document.querySelectorAll('.card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.card').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const v=btn.dataset.view;$('#rekapan').classList.toggle('hidden',v!=='rekapan');$('#rapor').classList.toggle('hidden',v!=='rapor')}));
$('#refresh').addEventListener('click',()=>loadBootstrap());
$('#search').addEventListener('input',renderClasses);$('#status').addEventListener('change',renderClasses);

async function request(action,payload={}){if(!state.api||!state.viewerKey)throw new Error('viewer_not_configured');const r=await fetch(state.api,{method:'POST',headers:{'Content-Type':'application/json','x-viewer-key':state.viewerKey},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({success:false,error:'invalid_response'}));if(!r.ok||j.success===false)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function loadBootstrap(){if(!state.api||!state.viewerKey){renderEmpty();return}try{const d=await request('bootstrap');state.period=d.period;state.classes=d.classes||[];$('#period').textContent=d.period?.label||'Periode aktif';renderSummary(d.summary||{});renderClasses();fillClassOptions()}catch(e){$('#classRows').innerHTML=`<tr><td colspan="5" class="empty">Tidak dapat memuat live report: ${esc(e.message)}</td></tr>`}}
function renderEmpty(){renderSummary({classes:0,classes_complete:0,students:0,students_incomplete:0});$('#classRows').innerHTML='<tr><td colspan="5" class="empty">Viewer aman sudah disiapkan. Endpoint read-only belum diaktifkan di produksi.</td></tr>'}
function renderSummary(s){$('#summary').innerHTML=`<div class="box"><small>Kelas</small><b>${s.classes||0}</b></div><div class="box"><small>Kelas Selesai</small><b>${s.classes_complete||0}</b></div><div class="box"><small>Siswa</small><b>${s.students||0}</b></div><div class="box"><small>Belum Lengkap</small><b>${s.students_incomplete||0}</b></div>`}
function renderClasses(){const q=($('#search').value||'').toLowerCase(),st=$('#status').value;const rows=state.classes.filter(x=>(!q||`${x.class_name} ${x.homeroom_teacher}`.toLowerCase().includes(q))&&(!st||x.status===st));$('#classRows').innerHTML=rows.length?rows.map(x=>`<tr><td><b>${esc(x.class_name)}</b></td><td>${esc(x.homeroom_teacher)}</td><td>${x.progress||0}% <span class="status ${x.status==='selesai'?'ok':'warn'}">${x.status==='selesai'?'Selesai':x.status==='belum'?'Belum mulai':'Belum lengkap'}</span></td><td>${x.incomplete_students||0} siswa</td><td><button class="mini-btn" onclick="openClass('${esc(x.class_id)}')">Lihat</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Tidak ada data.</td></tr>'}
function fillClassOptions(){const s=$('#reportClass');s.innerHTML='<option value="">Pilih kelas</option>'+state.classes.map(x=>`<option value="${esc(x.class_id)}">${esc(x.class_name)}</option>`).join('');s.onchange=()=>{const id=s.value;$('#previewClass').disabled=!id;if(id)openReportPicker(id)};$('#previewClass').onclick=()=>previewWholeClass(s.value)}
async function openClass(classId){try{const d=await request('class_detail',{class_id:classId});$('#detailTitle').textContent=d.class.name;$('#detailSub').textContent=`Walas: ${d.class.homeroom_teacher}`;$('#detailBody').innerHTML=`<table><thead><tr><th>Nama Siswa</th><th>Status</th><th>Kekurangan</th><th></th></tr></thead><tbody>${(d.students||[]).map(s=>`<tr><td><b>${esc(s.student_name)}</b><br><small>${esc(s.nisn||'')}</small></td><td><span class="status ${s.status==='lengkap'?'ok':'warn'}">${s.status==='lengkap'?'Lengkap':'Belum lengkap'}</span></td><td>${s.missing?.length?s.missing.map(m=>`<div class="missing"><b>${esc(m.label)}</b> — ${esc(m.owner)}${m.detail?`<br><small>${esc(m.detail)}</small>`:''}</div>`).join(''):'—'}</td><td><button class="mini-btn" onclick="previewReport('${esc(classId)}','${esc(s.student_id)}')">Lihat Rapor</button></td></tr>`).join('')}</tbody></table>`;detailDialog.showModal()}catch(e){alert(`Gagal membuka detail: ${e.message}`)}}
async function openReportPicker(classId){try{const d=await request('class_detail',{class_id:classId});$('#reportArea').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Nama Siswa</th><th>Status</th><th></th></tr></thead><tbody>${(d.students||[]).map(s=>`<tr><td>${esc(s.student_name)}</td><td>${s.status==='lengkap'?'Lengkap':'Belum lengkap'}</td><td><button class="mini-btn" onclick="previewReport('${esc(classId)}','${esc(s.student_id)}')">Preview</button></td></tr>`).join('')}</tbody></table></div>`}catch(e){$('#reportArea').textContent=`Gagal memuat siswa: ${e.message}`}}
async function previewReport(classId,studentId){try{const d=await request('report',{class_id:classId,student_id:studentId});const r=d.report;$('#reportArea').innerHTML=renderReport(r);document.querySelector('.card[data-view="rapor"]').click();detailDialog.open&&detailDialog.close()}catch(e){alert(`Gagal membuka rapor: ${e.message}`)}}
async function previewWholeClass(classId){if(!classId)return;try{const d=await request('class_reports',{class_id:classId});$('#reportArea').innerHTML=(d.reports||[]).map(renderReport).join('<div style="height:20px"></div>')}catch(e){$('#reportArea').textContent=`Gagal memuat rapor kelas: ${e.message}`}}
function renderReport(r){return `<article class="report-sheet"><h2>RAPOR ${esc(r.period?.report_type||'')}</h2><div style="text-align:center">SD Islam Tahfizh Cahaya Qur'an</div><div class="report-meta"><div><b>Nama</b>: ${esc(r.student?.name)}</div><div><b>Kelas</b>: ${esc(r.class?.name)}</div><div><b>NIS</b>: ${esc(r.student?.nis)}</div><div><b>NISN</b>: ${esc(r.student?.nisn)}</div><div><b>Periode</b>: ${esc(r.period?.label)}</div><div><b>Status</b>: ${r.status==='lengkap'?'Lengkap':'Draft / belum lengkap'}</div></div>${r.missing?.length?`<div class="missing"><b>Belum lengkap:</b> ${r.missing.map(x=>`${esc(x.label)} (${esc(x.owner)})`).join(', ')}</div>`:''}<h3>Akademik</h3><table class="report-table"><thead><tr><th>Mapel</th><th>Nilai</th><th>Status</th></tr></thead><tbody>${(r.academic||[]).map(x=>`<tr><td>${esc(x.subject_name)}</td><td>${x.average??'-'}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table><h3>Tahfizh</h3><p>${r.tahfizh?`${esc(r.tahfizh.materi_hafalan||'-')} · Realisasi: ${esc(r.tahfizh.realisasi_saat_ini||'-')}`:'Belum tersedia'}</p><h3>Absensi</h3><p>${r.attendance?.source_mode==='system'?'Mengikuti sistem':r.attendance?`Sakit ${r.attendance.sick_count||0}, Izin ${r.attendance.excused_count||0}, Alpa ${r.attendance.unexcused_count||0}`:'Belum tersedia'}</p><h3>Poin/Kesiswaan</h3><p>Reward: ${r.points?.reward_total||0} · Kedisiplinan: ${r.points?.discipline_total||0}</p><h3>Tanda Tangan</h3><p>Wali kelas: ${r.signatures?.homeroom?.exists?'✓':'Belum'} · Kepala sekolah: ${r.signatures?.principal?.exists?'✓':'Belum'}</p></article>`}
window.openClass=openClass;window.previewReport=previewReport;
renderEmpty();
