import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-session-token","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const T=(v:any)=>String(v??"").trim(),L=(v:any)=>T(v).toLowerCase();
const URL=Deno.env.get("SUPABASE_URL")!;
function key(){const p=Deno.env.get("SUPABASE_SECRET_KEYS");if(p){try{const x=JSON.parse(p);if(x?.default)return String(x.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||""}
const sb=createClient(URL,key(),{auth:{persistSession:false,autoRefreshToken:false}});
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const tok=T(req.headers.get("x-session-token"));if(!tok)return null;const{data:ss}=await sb.from("user_sessions").select("user_account_id,expires_at,revoked_at").eq("token_hash",await sha(tok)).maybeSingle();if(!ss||ss.revoked_at||!ss.expires_at||Date.parse(ss.expires_at)<=Date.now())return null;const{data:a}=await sb.from("user_accounts").select("id,teacher_id,username,status").eq("id",ss.user_account_id).maybeSingle();if(!a||["nonaktif","inactive","disabled","blocked"].includes(L(a.status)))return null;if(["hrd","admin"].includes(L(a.username)))return a;const{data:r}=await sb.from("user_account_roles").select("role_code,role,is_active").eq("user_account_id",a.id).eq("is_active",true);return (r||[]).some((x:any)=>["hrd","admin"].includes(L(x.role_code||x.role)))?a:null}
function hdr(req:Request){return{"Content-Type":"application/json","apikey":req.headers.get("apikey")||"","Authorization":req.headers.get("Authorization")||"","x-session-token":req.headers.get("x-session-token")||""}}
async function forwardAdmin(req:Request,b:any,timeoutMs=4500){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeoutMs);try{const r=await fetch(`${URL}/functions/v1/hrd-administration`,{method:"POST",headers:hdr(req),body:JSON.stringify(b),signal:ctrl.signal});const raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{d={success:false,error:"invalid_upstream"}}return{ok:r.ok&&d?.success!==false,status:r.status,data:d}}catch(e:any){return{ok:false,status:504,data:{success:false,error:e?.name==="AbortError"?"admin_timeout":"admin_unreachable"}}}finally{clearTimeout(timer)}}
const latest=(xs:any[],field="created_at")=>xs.map(x=>T(x?.[field]||x?.updated_at||x?.created_at)).filter(Boolean).sort().pop()||null;
function recalc(t:any){const req=(t.categories||[]).filter((c:any)=>c.applicable&&!c.excluded_from_missing),done=req.filter((c:any)=>c.status==="present").length,partial=req.filter((c:any)=>c.status==="partial").length,missing=req.filter((c:any)=>c.status==="missing").length;t.required_count=req.length;t.completed_count=done;t.partial_count=partial;t.missing_count=missing;t.issue_units=missing+partial;t.missing_categories=req.filter((c:any)=>c.status==="missing").map((c:any)=>c.label);t.partial_categories=req.filter((c:any)=>c.status==="partial").map((c:any)=>c.label);t.completeness_index=req.length?Math.round(((done+partial*.5)/req.length)*100):100}
function normalizeTimesheet(t:any){const c=(t.categories||[]).find((x:any)=>x.key==="timesheet");if(!c)return;const merged=[...(Array.isArray(c.items)?c.items:[]),...(Array.isArray(c.activity_items)?c.activity_items:[])];c.label="Timesheet";c.items=merged;c.item_count=merged.length;c.last_created_at=latest(merged)||c.last_created_at||null;c.status=merged.length?"present":"separate";c.applicable=true;c.excluded_from_missing=true;c.excluded_from_performance=true;c.note="Timesheet adalah timeline aktivitas kerja guru. JP hanya informasi beban mengajar, bukan penentu tunggal kelengkapan atau performa."}
async function signedPhoto(x:any){let photo_url="";if(x.storage_bucket&&x.storage_path){const{data}=await sb.storage.from(x.storage_bucket).createSignedUrl(x.storage_path,86400);photo_url=data?.signedUrl||""}return{id:x.id,title:"Foto Promosi",description:"",period_start:x.activity_date,period_end:x.activity_date,created_at:x.created_at||x.updated_at||null,photo_url,has_photo:!!photo_url}}
async function addPromotion(data:any,start:string,end:string){const{data:rows,error}=await sb.from("employee_promotion_reports").select("id,teacher_id,activity_date,title,description,storage_bucket,storage_path,created_at,updated_at").gte("activity_date",start).lte("activity_date",end).order("activity_date",{ascending:false});if(error)throw error;const by=new Map<string,any[]>();for(const x of rows||[]){const id=T(x.teacher_id);if(!id)continue;if(!by.has(id))by.set(id,[]);by.get(id)!.push(x)}for(const t of data.teachers||[]){normalizeTimesheet(t);const raw=by.get(T(t.teacher_id))||[],items=await Promise.all(raw.map(signedPhoto)),cat={key:"promotion",label:"Promosi Sekolah",applicable:true,status:items.length?"present":"missing",item_count:items.length,last_created_at:latest(items),items,granularity:"period",note:"Minimal 1 foto Promosi Socmed pada periode HRD."};t.categories=(t.categories||[]).filter((c:any)=>c.key!=="promotion");t.categories.push(cat);recalc(t)}const all=data.teachers||[];data.summary={...(data.summary||{}),teachers:all.length,with_issues:all.filter((t:any)=>t.missing_count||t.partial_count).length,clean:all.filter((t:any)=>!t.missing_count&&!t.partial_count).length,missing_category_units:all.reduce((n:number,t:any)=>n+Number(t.missing_count||0),0),promotion_complete:all.filter((t:any)=>(t.categories||[]).find((c:any)=>c.key==="promotion")?.status==="present").length,promotion_missing:all.filter((t:any)=>(t.categories||[]).find((c:any)=>c.key==="promotion")?.status==="missing").length};data.priority=all.filter((t:any)=>t.missing_count||t.partial_count).sort((a:any,b:any)=>Number(b.issue_units||0)-Number(a.issue_units||0)||T(a.name).localeCompare(T(b.name),"id"));return data}
async function fallback(start:string,end:string){
  const[{data:unit},{data:year}]=await Promise.all([sb.from("school_units").select("id,code").eq("code","SD").maybeSingle(),sb.from("academic_years").select("id,name,start_date,end_date,school_unit_id").eq("is_active",true).maybeSingle()]);
  if(!year)throw Error("active_period_missing");const{data:sem}=await sb.from("semesters").select("id,semester_no,start_date,end_date").eq("academic_year_id",year.id).eq("is_active",true).maybeSingle();const sn=Number(sem?.semester_no||1);
  const[tr,ua,cl,as,ra,rpp,acts,roster,tah,pj,promo]=await Promise.all([
    sb.from("teachers").select("id,full_name,teacher_code,position,status").order("full_name"),
    sb.from("user_accounts").select("id,teacher_id,username,status"),
    sb.from("classes").select("id,name,grade_level,is_active"),
    sb.from("teacher_subject_assignments").select("teacher_id,class_id,subject_id").eq("academic_year_id",year.id).eq("semester_no",sn).eq("is_active",true),
    sb.from("report_class_assignments").select("class_id,homeroom_teacher_id,partner_teacher_id").eq("academic_year_id",year.id).eq("semester_no",sn),
    sb.from("rpp_submissions").select("id,teacher_id,class_id,subject_id,original_filename,uploaded_at,created_at,updated_at").eq("upload_status","uploaded"),
    sb.from("teacher_timesheet_activities").select("id,teacher_id,work_date,activity,note,created_at,updated_at").gte("work_date",start).lte("work_date",end),
    sb.from("partner_tahfizh_halaqah_roster").select("partner_teacher_id,class_id,student_id").eq("academic_year_id",year.id).eq("semester_no",sn).eq("is_active",true),
    sb.from("tahfizh_monthly_progress").select("teacher_name,class_id,student_id,report_month,created_at,updated_at").eq("academic_year_id",year.id).eq("semester_no",sn),
    sb.from("pjbl_logs").select("id,class_id,logged_at,actual_activity,planned_activity,created_at,updated_at").eq("academic_year_id",year.id).eq("semester_no",sn).gte("logged_at",start+"T00:00:00").lte("logged_at",end+"T23:59:59"),
    sb.from("employee_promotion_reports").select("id,teacher_id,activity_date,title,description,storage_bucket,storage_path,created_at,updated_at").gte("activity_date",start).lte("activity_date",end)
  ]);for(const q of[tr,ua,cl,as,ra,rpp,acts,roster,tah,pj,promo])if(q.error)throw q.error;
  const accounts=ua.data||[],userByTeacher=new Map(accounts.filter((x:any)=>x.teacher_id).map((x:any)=>[T(x.teacher_id),x])),classMap=new Map((cl.data||[]).map((x:any)=>[T(x.id),x.name]));
  const teachers=(tr.data||[]).filter((x:any)=>!["nonaktif","inactive","disabled"].includes(L(x.status))&&L(userByTeacher.get(T(x.id))?.username)!=="hrd");
  const scoreCounts=await Promise.all(teachers.map(async(t:any)=>{const{count}=await sb.from("academic_scores").select("id",{head:true,count:"exact"}).eq("academic_year_id",year.id).eq("semester_no",sn).eq("teacher_id",t.id).is("deleted_at",null);return[t.id,Number(count||0)] as const}));const scoreMap=new Map(scoreCounts);
  const n=(v:any)=>T(v).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
  const out=await Promise.all(teachers.map(async(t:any)=>{const id=T(t.id),asg=(as.data||[]).filter((x:any)=>T(x.teacher_id)===id),classes=[...new Set(asg.map((x:any)=>classMap.get(T(x.class_id))).filter(Boolean))];const rr=(rpp.data||[]).filter((x:any)=>T(x.teacher_id)===id),aa=(acts.data||[]).filter((x:any)=>T(x.teacher_id)===id),sc=Number(scoreMap.get(id)||0),rs=(roster.data||[]).filter((x:any)=>T(x.partner_teacher_id)===id),th=(tah.data||[]).filter((x:any)=>n(x.teacher_name)===n(t.full_name)),home=(ra.data||[]).filter((x:any)=>T(x.homeroom_teacher_id)===id).map((x:any)=>T(x.class_id)),pp=(pj.data||[]).filter((x:any)=>home.includes(T(x.class_id))),pr=(promo.data||[]).filter((x:any)=>T(x.teacher_id)===id);const mk=(key:string,label:string,app:boolean,count:number,items:any[]=[],gran="period",note="")=>({key,label,applicable:app,status:!app?"na":count>0?"present":"missing",item_count:count,last_created_at:latest(items),items,granularity:gran,note});const tsItems=aa.map((x:any)=>({id:x.id,title:x.activity||"Aktivitas",description:x.note||"",period_start:x.work_date,created_at:x.created_at||x.updated_at}));const promoItems=await Promise.all(pr.map(signedPhoto));const ts={key:"timesheet",label:"Timesheet",applicable:true,status:tsItems.length?"present":"separate",item_count:tsItems.length,last_created_at:latest(tsItems),items:tsItems,granularity:"daily",excluded_from_missing:true,excluded_from_performance:true,note:"Timeline kerja guru; tidak dinilai dari JP saja."};const cats=[mk("rpp","RPP",asg.length>0,rr.length,rr.map((x:any)=>({id:x.id,title:x.original_filename||"RPP",description:classMap.get(T(x.class_id))||"",created_at:x.uploaded_at||x.created_at})),"lp_period","Status fallback cepat: membaca RPP terunggah."),ts,mk("academic","Capaian & Kognitif",asg.length>0,sc,[],"semester","Status fallback cepat: membaca jumlah nilai yang tersimpan."),mk("tahfizh","Tahfizh",rs.length>0,th.length,[],"monthly"),mk("bilingual","Bilingual",false,0,[],"semester"),mk("pjbl","PBL / Market Day",home.length>0,pp.length,pp.map((x:any)=>({id:x.id,title:"PBL / Market Day",description:x.actual_activity||x.planned_activity||"",period_start:T(x.logged_at).slice(0,10),created_at:x.created_at||x.updated_at})),"daily"),{key:"promotion",label:"Promosi Sekolah",applicable:true,status:promoItems.length?"present":"missing",item_count:promoItems.length,last_created_at:latest(promoItems),items:promoItems,granularity:"period",note:"Minimal 1 foto Promosi Socmed pada periode HRD."}];const row={teacher_id:id,name:t.full_name,teacher_code:t.teacher_code||"",position:t.position||"",username:userByTeacher.get(id)?.username||"",classes,categories:cats,context_categories:[]};recalc(row);return row}));
  const summary={teachers:out.length,with_issues:out.filter((x:any)=>x.missing_count||x.partial_count).length,clean:out.filter((x:any)=>!x.missing_count&&!x.partial_count).length,missing_category_units:out.reduce((z:number,x:any)=>z+Number(x.missing_count||0),0),promotion_complete:out.filter((x:any)=>x.categories.find((c:any)=>c.key==="promotion")?.status==="present").length,promotion_missing:out.filter((x:any)=>x.categories.find((c:any)=>c.key==="promotion")?.status==="missing").length};return{success:true,live:true,fallback_fast:true,range:{start,end},source_period:{academic_year:year.name,semester_no:sn,semester_start:sem?.start_date||year.start_date,semester_end:sem?.end_date||year.end_date,semester_dates_derived:false},summary,teachers:out,priority:out.filter((x:any)=>x.missing_count||x.partial_count).sort((a:any,b:any)=>b.issue_units-a.issue_units||T(a.name).localeCompare(T(b.name),"id"))}}


async function reportPeriods(action:string,b:any,me:any){
 if(action==="period_list"){const{data,error}=await sb.from("hrd_report_periods").select("*").order("start_date",{ascending:false});if(error)throw error;return{success:true,periods:data||[]}}
 if(action==="period_save"){const name=T(b.name),start=T(b.start_date),end=T(b.end_date),id=T(b.id);if(!name||!/^\\d{4}-\\d{2}-\\d{2}$/.test(start)||!/^\\d{4}-\\d{2}-\\d{2}$/.test(end)||end<start)return{success:false,error:"invalid_period"};let oq=sb.from("hrd_report_periods").select("id,name,start_date,end_date").lte("start_date",end).gte("end_date",start);if(id)oq=oq.neq("id",id);const{data:over}=await oq;if((over||[]).length)return{success:false,error:"period_overlap",overlap:over};if(b.is_active)await sb.from("hrd_report_periods").update({is_active:false}).neq("id",id||"00000000-0000-0000-0000-000000000000");const row={name,start_date:start,end_date:end,is_active:!!b.is_active,updated_at:new Date().toISOString(),created_by:me.id};const q=id?sb.from("hrd_report_periods").update(row).eq("id",id).select().single():sb.from("hrd_report_periods").insert(row).select().single();const{data,error}=await q;if(error)throw error;return{success:true,period:data}}
 if(action==="promotion_center"){let start=T(b.start),end=T(b.end);if(!start||!end){const{data:p}=await sb.from("hrd_report_periods").select("*").eq("is_active",true).maybeSingle();if(!p)return{success:false,error:"no_active_period"};start=p.start_date;end=p.end_date}const[{data:accounts,error:accountsError},{data:teachers,error:teachersError},{data:roles,error:rolesError},{data:promos,error:promosError}]=await Promise.all([sb.from("user_accounts").select("id,teacher_id,username,status"),sb.from("teachers").select("id,full_name,position,status"),sb.from("user_account_roles").select("user_account_id,role_code,role,is_active").eq("is_active",true),sb.from("employee_promotion_reports").select("*").gte("activity_date",start).lte("activity_date",end).order("created_at",{ascending:false})]);if(accountsError)throw accountsError;if(promosError)throw promosError;const teacherMap=new Map((teachers||[]).map((t:any)=>[T(t.id),t]));const rm=new Map<string,string[]>();for(const r of roles||[]){const a=rm.get(r.user_account_id)||[];a.push(T(r.role_code||r.role));rm.set(r.user_account_id,a)}const wanted=["pimpinan","kepala_sekolah","kepsek","akademik","kegiatan","kesiswaan","tahfizh","walas","guru","mapel","partner","guru_tahfizh"];const promoAccountIds=new Set((promos||[]).map((p:any)=>T(p.user_account_id)).filter(Boolean));const promoTeacherIds=new Set((promos||[]).map((p:any)=>T(p.teacher_id)).filter(Boolean));const people=(accounts||[]).filter((u:any)=>!["nonaktif","inactive","disabled","blocked"].includes(L(u.status))&&!["admin","hrd"].includes(L(u.username))||(promoAccountIds.has(T(u.id))||(u.teacher_id&&promoTeacherIds.has(T(u.teacher_id)))));const rows=await Promise.all(people.map(async(u:any)=>{const ps=(promos||[]).filter((p:any)=>T(p.user_account_id)===T(u.id)||(u.teacher_id&&T(p.teacher_id)===T(u.teacher_id)));const items=await Promise.all(ps.map(async(p:any)=>{let photo_url="";if(p.storage_bucket&&p.storage_path){const{data}=await sb.storage.from(p.storage_bucket).createSignedUrl(p.storage_path,3600);photo_url=data?.signedUrl||""}return{...p,photo_url}}));const teacher=teacherMap.get(T(u.teacher_id));return{id:u.id,name:teacher?.full_name||u.username,position:teacher?.position||"",roles:rm.get(u.id)||[],count:items.length,status:items.length?"sudah":"belum",items}}));return{success:true,range:{start,end},summary:{people:rows.length,done:rows.filter(x=>x.count).length,missing:rows.filter(x=>!x.count).length,uploads:rows.reduce((n,x)=>n+x.count,0)},rows}}
 return null;
}

async function reportGrades(b:any){
 const semester=Number(b.semester_no||1);if(![1,2].includes(semester))return{success:false,error:"invalid_semester"};
 const reportType=T(b.report_type||"STS").toUpperCase(),allowed=semester===1?["STS","SAS"]:["STS","SAT"];if(!allowed.includes(reportType))return{success:false,error:"invalid_report_type"};
 const{data:year,error:ye}=await sb.from("academic_years").select("id,name").eq("is_active",true).maybeSingle();if(ye)throw ye;if(!year)return{success:false,error:"active_year_missing"};
 const [cq,sq,eq,subq,aq,tq,loq,waq]=await Promise.all([
  sb.from("classes").select("id,name,grade_level").eq("academic_year_id",year.id).eq("is_active",true).order("grade_level").order("name"),
  sb.from("students").select("id,full_name,nis,status"),
  sb.from("student_enrollments").select("student_id,class_id").eq("academic_year_id",year.id).eq("semester_no",semester).eq("is_active",true),
  sb.from("subjects").select("id,name,grade_level,sort_order").eq("is_active",true).order("sort_order"),
  sb.from("teacher_subject_assignments").select("teacher_id,class_id,subject_id").eq("academic_year_id",year.id).eq("semester_no",semester).eq("is_active",true),
  sb.from("teachers").select("id,full_name,status"),
  sb.from("learning_objectives").select("id,subject_id,grade_level,code,description,sort_order").eq("academic_year_id",year.id).eq("semester_no",semester).eq("objective_type","TP").eq("is_active",true).order("sort_order"),
  sb.from("teacher_assignments").select("teacher_id,class_id").eq("academic_year_id",year.id).eq("semester_no",semester).eq("assignment_type","WALAS").eq("is_active",true)
 ]);for(const q of[cq,sq,eq,subq,aq,tq,loq,waq])if(q.error)throw q.error;
 const scores:any[]=[];for(let from=0;;from+=1000){const{data,error}=await sb.from("academic_scores").select("student_id,class_id,subject_id,score,learning_objective_id").eq("academic_year_id",year.id).eq("semester_no",semester).eq("assessment_type","TP").is("deleted_at",null).range(from,from+999);if(error)throw error;scores.push(...(data||[]));if((data||[]).length<1000)break}
 const students=new Map((sq.data||[]).filter((x:any)=>!["inactive","nonaktif","keluar"].includes(L(x.status))).map((x:any)=>[T(x.id),x])),teachers=new Map((tq.data||[]).map((x:any)=>[T(x.id),T(x.full_name)]));
 const byGrade=new Map<number,any[]>();for(const s of subq.data||[]){const g=Number(s.grade_level);if(!byGrade.has(g))byGrade.set(g,[]);byGrade.get(g)!.push(s)}
 const loBySubject=new Map<string,any[]>();for(const lo of loq.data||[]){const k=T(lo.subject_id),z=loBySubject.get(k)||[];z.push(lo);loBySubject.set(k,z)}
 const teacherBy=new Map<string,string[]>();for(const a of aq.data||[]){const k=T(a.class_id)+"|"+T(a.subject_id),name=teachers.get(T(a.teacher_id));if(!name)continue;const z=teacherBy.get(k)||[];if(!z.includes(name))z.push(name);teacherBy.set(k,z)}
 const vals=new Map<string,number[]>(),tpVals=new Map<string,number[]>();for(const s of scores){if(s.score===null||!Number.isFinite(Number(s.score)))continue;const sid=T(s.student_id),cid=T(s.class_id),sub=T(s.subject_id),lo=T(s.learning_objective_id),v=Number(s.score),k=sid+"|"+cid+"|"+sub,z=vals.get(k)||[];z.push(v);vals.set(k,z);if(lo){const tk=sid+"|"+cid+"|"+sub+"|"+lo,tz=tpVals.get(tk)||[];tz.push(v);tpVals.set(tk,tz)}}
 const roster=new Map<string,string[]>();for(const e of eq.data||[]){if(!students.has(T(e.student_id)))continue;const z=roster.get(T(e.class_id))||[];z.push(T(e.student_id));roster.set(T(e.class_id),z)}
 const walasBy=new Map<string,string[]>();for(const a of waq.data||[]){const name=teachers.get(T(a.teacher_id));if(!name)continue;const k=T(a.class_id),z=walasBy.get(k)||[];if(!z.includes(name))z.push(name);walasBy.set(k,z)}
 const rows:any[]=[],classes:any[]=[];for(const c of cq.data||[]){
  const expected=byGrade.get(Number(c.grade_level))||[],ids=roster.get(T(c.id))||[],subjectMeta=new Map<string,any>();
  for(const sub of expected){const sid=T(sub.id),los=(loBySubject.get(sid)||[]).filter((lo:any)=>Number(lo.grade_level)===Number(c.grade_level));const tps=los.map((lo:any)=>{const filled=ids.filter(stid=>(tpVals.get(stid+"|"+T(c.id)+"|"+sid+"|"+T(lo.id))||[]).length>0).length,pct=ids.length?filled/ids.length:0;return{tp_id:T(lo.id),code:T(lo.code)||"TP",description:T(lo.description),filled,total:ids.length,percent:Math.round(pct*1000)/10,state:filled===0?"empty":pct<0.5?"inputting":filled<ids.length?"started":"complete",counts_for_completeness:pct>=0.5}});subjectMeta.set(sid,{tps,started_tps:tps.filter((x:any)=>x.counts_for_completeness).length,has_any_score:ids.some(stid=>(vals.get(stid+"|"+T(c.id)+"|"+sid)||[]).length>0)})}
  const sr:any[]=[];for(const sid of ids){const st:any=students.get(sid),subjects=expected.map((sub:any)=>{const subid=T(sub.id),meta=subjectMeta.get(subid),all=(vals.get(sid+"|"+T(c.id)+"|"+subid)||[]),studentTps=(meta.tps||[]).map((tp:any)=>{const a=tpVals.get(sid+"|"+T(c.id)+"|"+subid+"|"+tp.tp_id)||[];return{...tp,score:a.length?Math.round(a.reduce((x:number,y:number)=>x+y,0)/a.length*100)/100:null}}),counted=studentTps.filter((tp:any)=>tp.counts_for_completeness),missingTp=counted.filter((tp:any)=>tp.score===null).length,score=all.length?Math.round(all.reduce((x:number,y:number)=>x+y,0)/all.length*100)/100:null;return{subject_id:subid,subject_name:T(sub.name),score,teachers:teacherBy.get(T(c.id)+"|"+subid)||[],tps:studentTps,tp_total:studentTps.length,tp_started:meta.started_tps,tp_filled:studentTps.filter((x:any)=>x.score!==null).length,has_any_score:meta.has_any_score,counts_for_status:meta.started_tps>0,missing_tp_count:missingTp}}),missing=subjects.filter((x:any)=>x.counts_for_status&&x.missing_tp_count>0),below=subjects.filter((x:any)=>x.score!==null&&x.score<80),filled=subjects.filter((x:any)=>x.score!==null),average=filled.length?Math.round(filled.reduce((n:number,x:any)=>n+Number(x.score),0)/filled.length*100)/100:null,status=below.length?"not_complete":missing.length?"incomplete":filled.length?"complete":"no_score";sr.push({student_id:sid,student_name:T(st.full_name),average,status,missing_count:missing.length,below_count:below.length,subjects})}
  sr.sort((a,b)=>T((students.get(a.student_id) as any)?.nis).localeCompare(T((students.get(b.student_id) as any)?.nis),"id",{numeric:true})||a.student_name.localeCompare(b.student_name,"id"));sr.forEach((x,i)=>{x.class_no=i+1;rows.push({...x,class_id:T(c.id),class_name:T(c.name),grade_level:Number(c.grade_level)})});const complete=sr.filter(x=>x.status==="complete").length,incomplete=sr.filter(x=>x.status==="incomplete").length,notComplete=sr.filter(x=>x.status==="not_complete").length,noScore=sr.filter(x=>x.status==="no_score").length,teacherNames=[...new Set((aq.data||[]).filter((a:any)=>T(a.class_id)===T(c.id)).map((a:any)=>teachers.get(T(a.teacher_id))).filter(Boolean))];classes.push({class_id:T(c.id),class_name:T(c.name),grade_level:Number(c.grade_level),homeroom_teachers:walasBy.get(T(c.id))||[],teachers:teacherNames,students:sr.length,complete,not_complete:notComplete,incomplete,no_score:noScore,percent:(complete+notComplete)>0?Math.round(complete/(complete+notComplete)*1000)/10:0,status:notComplete>0?"not_complete":incomplete>0?"incomplete":complete>0?"complete":"no_score"})
 }
 return{success:true,academic_year:year.name,semester_no:semester,report_type:reportType,threshold:80,tp_start_threshold:50,classes,rows}
}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return J({success:false,error:"method_not_allowed"},405);try{const me=await auth(req);if(!me)return J({success:false,error:"session_invalid"},401);const b=await req.json().catch(()=>({})),action=L(b.action||"administration");if(action==="report_grades"){const z=await reportGrades(b);return J(z,z?.success===false?400:200)}if(["period_list","period_save","promotion_center"].includes(action)){const z=await reportPeriods(action,b,me);return J(z,z?.success===false?400:200)}if(action==="rpp_file"){const x=await forwardAdmin(req,b,10000);return J(x.data,x.status)}if(action!=="administration")return J({success:false,error:"forbidden"},403);const start=T(b.start),end=T(b.end);if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start>end)return J({success:false,error:"invalid_date_range"},400);const x=await forwardAdmin(req,b,4500);if(x.ok){try{return J(await addPromotion(x.data,start,end))}catch(e){console.warn("promotion enrichment failed",e);for(const t of x.data?.teachers||[]){normalizeTimesheet(t);recalc(t)}return J(x.data)}}console.warn("hrd-administration slow/unavailable; using fast fallback",x.data?.error);return J(await fallback(start,end))}catch(e){console.error("hrd-live-report",e);return J({success:false,error:"server_error",message:T((e as any)?.message)||"internal_error"},500)}});
